project_id = "ndacklcbzjfycwigdpfk"

[functions.openai-chat]
verify_jwt = false

[functions.background-monitor]
verify_jwt = false

[functions.scheduled-monitor]
verify_jwt = false

[functions.binance-klines]
verify_jwt = false