import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh' | 'es' | 'ja' | 'ko' | 'fr' | 'de' | 'it' | 'pt' | 'ru' | 'ar' | 'hi' | 'th' | 'vi' | 'tr' | 'nl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-IN-1 Ultimate Brain Making Money Easier',
    'portfolio.total': 'Total Portfolio',
    'portfolio.change': '24h Change',
    'portfolio.trades': 'Active Trades',
    'market.overview': 'Market Overview',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Quick Actions',
    'actions.execute': 'Execute Trade',
    'actions.analysis': 'Portfolio Analysis',
    'actions.risk': 'Risk Assessment',
    'actions.alerts': 'Market Alerts',
    'status.live': 'Live Market Data',
    'advisor.confidence': 'Confident',
    'advisor.recommendation': 'Recommendation',
    'advisor.analysis': 'AI Analysis',
    'advisor.detailed': 'Get Detailed Analysis',
    'advisor.featured': '⭐ Featured',
    'ai.communicate': 'Start Communication',
    'wallet.connect': 'Connect Wallet',
    'wallet.real': 'Real Portfolio',
    'wallet.virtual': 'Virtual Trading Portfolio',
    'trading.spot': 'Spot Trading',
    'trading.futures': 'Futures Trading',
    'trading.options': 'Options Trading',
    'ai.autotrader': 'AI Auto Trading',
    // Upcoming Advisors section
    'advisors.more_models': 'More Character Models',
    'advisors.not_alone': 'You Are Not Fighting Alone',
    'advisors.coming_soon': 'Coming Soon - Elite Warriors Assembling',
    'advisors.trump.name': 'Donald Trump',
    'advisors.trump.specialty': 'Business Empire Strategist',
    'advisors.trump.expertise': 'Business Empire',
    'advisors.trump.status': '🔧 In Development',
    'advisors.quantitative.name': 'Quantitative Trading Master',
    'advisors.quantitative.specialty': 'Algorithmic Trading Expert',
    'advisors.quantitative.expertise': 'Quantitative Strategy',
    'advisors.crypto.name': 'Crypto Currency King',
    'advisors.crypto.specialty': 'Web3 Investment Mentor',
    'advisors.crypto.expertise': 'Digital Assets',
    'advisors.macro.name': 'Macro Economic Master',
    'advisors.macro.specialty': 'Global Strategy Analyst',
    'advisors.macro.expertise': 'Macro Strategy',
    'advisors.coming_soon_status': '⏳ Coming Soon'
  },
  zh: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3合1终极大脑让赚钱更简单',
    'portfolio.total': '总投资组合',
    'portfolio.change': '24小时变化',
    'portfolio.trades': '活跃交易',
    'market.overview': '市场概览',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': '快速操作',
    'actions.execute': '执行交易',
    'actions.analysis': '投资组合分析',
    'actions.risk': '风险评估',
    'actions.alerts': '市场提醒',
    'status.live': '实时市场数据',
    'advisor.confidence': '置信度',
    'advisor.recommendation': '推荐',
    'advisor.analysis': 'AI分析',
    'advisor.detailed': '获取详细分析',
    'advisor.featured': '⭐ 精选',
    'ai.communicate': '开始沟通',
    'wallet.connect': '连接钱包',
    'wallet.real': '真实投资组合',
    'wallet.virtual': '虚拟交易组合',
    'trading.spot': '现货交易',
    'trading.futures': '合约交易',
    'trading.options': '期权交易',
    'ai.autotrader': 'AI自动交易',
    // Upcoming Advisors section
    'advisors.more_models': '更多人物模型',
    'advisors.not_alone': '你不再是一个人战斗',
    'advisors.coming_soon': '敬请期待 - 顶级战友集结中',
    'advisors.trump.name': 'Donald Trump',
    'advisors.trump.specialty': '商业帝国战略大师',
    'advisors.trump.expertise': '商业帝国',
    'advisors.trump.status': '🔧 正在开发中',
    'advisors.quantitative.name': '量化交易大师',
    'advisors.quantitative.specialty': '算法交易专家',
    'advisors.quantitative.expertise': '量化策略',
    'advisors.crypto.name': '加密货币之王',
    'advisors.crypto.specialty': 'Web3投资导师',
    'advisors.crypto.expertise': '数字资产',
    'advisors.macro.name': '宏观经济大师',
    'advisors.macro.specialty': '全球策略分析师',
    'advisors.macro.expertise': '宏观策略',
    'advisors.coming_soon_status': '⏳ 即将到来'
  },
  es: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3 EN 1 Cerebro Ultimate que Hace Ganar Dinero Más Fácil',
    'portfolio.total': 'Portafolio Total',
    'portfolio.change': 'Cambio 24h',
    'portfolio.trades': 'Operaciones Activas',
    'market.overview': 'Resumen del Mercado',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Acciones Rápidas',
    'actions.execute': 'Ejecutar Operación',
    'actions.analysis': 'Análisis de Portafolio',
    'actions.risk': 'Evaluación de Riesgo',
    'actions.alerts': 'Alertas de Mercado',
    'status.live': 'Datos de Mercado en Vivo',
    'advisor.confidence': 'Confianza',
    'advisor.recommendation': 'Recomendación',
    'advisor.analysis': 'Análisis AI',
    'advisor.detailed': 'Obtener Análisis Detallado',
    'advisor.featured': '⭐ Destacado',
    'ai.communicate': 'Iniciar Comunicación',
    'wallet.connect': 'Conectar Billetera',
    'wallet.real': 'Portafolio Real',
    'wallet.virtual': 'Portafolio de Trading Virtual',
    'trading.spot': 'Trading al Contado',
    'trading.futures': 'Trading de Futuros',
    'trading.options': 'Trading de Opciones',
    'ai.autotrader': 'Trading Automático AI'
  },
  ja: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-IN-1アルティメット・ブレインでお金稼ぎがより簡単に',
    'portfolio.total': '総ポートフォリオ',
    'portfolio.change': '24時間変動',
    'portfolio.trades': 'アクティブトレード',
    'market.overview': 'マーケット概要',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'クイックアクション',
    'actions.execute': 'トレード実行',
    'actions.analysis': 'ポートフォリオ分析',
    'actions.risk': 'リスク評価',
    'actions.alerts': 'マーケットアラート',
    'status.live': 'ライブマーケットデータ',
    'advisor.confidence': '信頼度',
    'advisor.recommendation': '推奨',
    'advisor.analysis': 'AI分析',
    'advisor.detailed': '詳細分析を取得',
    'advisor.featured': '⭐ 注目',
    'ai.communicate': 'コミュニケーション開始',
    'wallet.connect': 'ウォレット接続',
    'wallet.real': '実際のポートフォリオ',
    'wallet.virtual': 'バーチャルトレーディングポートフォリオ',
    'trading.spot': 'スポット取引',
    'trading.futures': '先物取引',
    'trading.options': 'オプション取引',
    'ai.autotrader': 'AI自動取引'
  },
  ko: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-IN-1 궁극의 두뇌로 돈 벌기가 더 쉬워집니다',
    'portfolio.total': '총 포트폴리오',
    'portfolio.change': '24시간 변동',
    'portfolio.trades': '활성 거래',
    'market.overview': '시장 개요',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': '빠른 액션',
    'actions.execute': '거래 실행',
    'actions.analysis': '포트폴리오 분석',
    'actions.risk': '위험 평가',
    'actions.alerts': '시장 알림',
    'status.live': '실시간 시장 데이터',
    'advisor.confidence': '신뢰도',
    'advisor.recommendation': '추천',
    'advisor.analysis': 'AI 분석',
    'advisor.detailed': '상세 분석 받기',
    'advisor.featured': '⭐ 특집',
    'ai.communicate': '소통 시작',
    'wallet.connect': '지갑 연결',
    'wallet.real': '실제 포트폴리오',
    'wallet.virtual': '가상 거래 포트폴리오',
    'trading.spot': '현물 거래',
    'trading.futures': '선물 거래',
    'trading.options': '옵션 거래',
    'ai.autotrader': 'AI 자동 거래'
  },
  fr: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-EN-1 Cerveau Ultime Rendant l\'Argent Plus Facile',
    'portfolio.total': 'Portefeuille Total',
    'portfolio.change': 'Changement 24h',
    'portfolio.trades': 'Trades Actifs',
    'market.overview': 'Aperçu du Marché',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Actions Rapides',
    'actions.execute': 'Exécuter le Trade',
    'actions.analysis': 'Analyse du Portefeuille',
    'actions.risk': 'Évaluation des Risques',
    'actions.alerts': 'Alertes du Marché',
    'status.live': 'Données de Marché en Direct',
    'advisor.confidence': 'Confiance',
    'advisor.recommendation': 'Recommandation',
    'advisor.analysis': 'Analyse IA',
    'advisor.detailed': 'Obtenir une Analyse Détaillée',
    'advisor.featured': '⭐ Vedette',
    'ai.communicate': 'Commencer la Communication',
    'wallet.connect': 'Connecter le Portefeuille',
    'wallet.real': 'Portefeuille Réel',
    'wallet.virtual': 'Portefeuille de Trading Virtuel',
    'trading.spot': 'Trading au Comptant',
    'trading.futures': 'Trading de Contrats à Terme',
    'trading.options': 'Trading d\'Options',
    'ai.autotrader': 'Trading Automatique IA'
  },
  de: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-IN-1 Ultimatives Gehirn Macht Geld Verdienen Einfacher',
    'portfolio.total': 'Gesamtportfolio',
    'portfolio.change': '24h Änderung',
    'portfolio.trades': 'Aktive Trades',
    'market.overview': 'Marktübersicht',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Schnelle Aktionen',
    'actions.execute': 'Trade Ausführen',
    'actions.analysis': 'Portfolio-Analyse',
    'actions.risk': 'Risikobewertung',
    'actions.alerts': 'Markt-Benachrichtigungen',
    'status.live': 'Live-Marktdaten',
    'advisor.confidence': 'Vertrauen',
    'advisor.recommendation': 'Empfehlung',
    'advisor.analysis': 'KI-Analyse',
    'advisor.detailed': 'Detaillierte Analyse Erhalten',
    'advisor.featured': '⭐ Empfohlen',
    'ai.communicate': 'Kommunikation Starten',
    'wallet.connect': 'Wallet Verbinden',
    'wallet.real': 'Echtes Portfolio',
    'wallet.virtual': 'Virtuelles Trading-Portfolio',
    'trading.spot': 'Spot-Trading',
    'trading.futures': 'Futures-Trading',
    'trading.options': 'Options-Trading',
    'ai.autotrader': 'KI-Auto-Trading'
  },
  it: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-IN-1 Cervello Supremo Rende Fare Soldi Più Facile',
    'portfolio.total': 'Portfolio Totale',
    'portfolio.change': 'Cambio 24h',
    'portfolio.trades': 'Trade Attivi',
    'market.overview': 'Panoramica del Mercato',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Azioni Rapide',
    'actions.execute': 'Esegui Trade',
    'actions.analysis': 'Analisi del Portfolio',
    'actions.risk': 'Valutazione del Rischio',
    'actions.alerts': 'Avvisi di Mercato',
    'status.live': 'Dati di Mercato in Tempo Reale',
    'advisor.confidence': 'Fiducia',
    'advisor.recommendation': 'Raccomandazione',
    'advisor.analysis': 'Analisi IA',
    'advisor.detailed': 'Ottieni Analisi Dettagliata',
    'advisor.featured': '⭐ In Evidenza',
    'ai.communicate': 'Inizia Comunicazione',
    'wallet.connect': 'Connetti Wallet',
    'wallet.real': 'Portfolio Reale',
    'wallet.virtual': 'Portfolio di Trading Virtuale',
    'trading.spot': 'Trading Spot',
    'trading.futures': 'Trading Futures',
    'trading.options': 'Trading Opzioni',
    'ai.autotrader': 'Trading Automatico IA'
  },
  pt: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-EM-1 Cérebro Supremo Torna Ganhar Dinheiro Mais Fácil',
    'portfolio.total': 'Portfolio Total',
    'portfolio.change': 'Mudança 24h',
    'portfolio.trades': 'Trades Ativos',
    'market.overview': 'Visão Geral do Mercado',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Ações Rápidas',
    'actions.execute': 'Executar Trade',
    'actions.analysis': 'Análise do Portfolio',
    'actions.risk': 'Avaliação de Risco',
    'actions.alerts': 'Alertas do Mercado',
    'status.live': 'Dados de Mercado ao Vivo',
    'advisor.confidence': 'Confiança',
    'advisor.recommendation': 'Recomendação',
    'advisor.analysis': 'Análise IA',
    'advisor.detailed': 'Obter Análise Detalhada',
    'advisor.featured': '⭐ Destaque',
    'ai.communicate': 'Iniciar Comunicação',
    'wallet.connect': 'Conectar Carteira',
    'wallet.real': 'Portfolio Real',
    'wallet.virtual': 'Portfolio de Trading Virtual',
    'trading.spot': 'Trading à Vista',
    'trading.futures': 'Trading de Futuros',
    'trading.options': 'Trading de Opções',
    'ai.autotrader': 'Trading Automático IA'
  },
  ru: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-В-1 Верховный Мозг Делает Зарабатывание Денег Проще',
    'portfolio.total': 'Общий Портфель',
    'portfolio.change': 'Изменение за 24ч',
    'portfolio.trades': 'Активные Сделки',
    'market.overview': 'Обзор Рынка',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Быстрые Действия',
    'actions.execute': 'Выполнить Сделку',
    'actions.analysis': 'Анализ Портфеля',
    'actions.risk': 'Оценка Рисков',
    'actions.alerts': 'Рыночные Оповещения',
    'status.live': 'Данные Рынка в Реальном Времени',
    'advisor.confidence': 'Уверенность',
    'advisor.recommendation': 'Рекомендация',
    'advisor.analysis': 'ИИ Анализ',
    'advisor.detailed': 'Получить Детальный Анализ',
    'advisor.featured': '⭐ Рекомендуемое',
    'ai.communicate': 'Начать Общение',
    'wallet.connect': 'Подключить Кошелек',
    'wallet.real': 'Реальный Портфель',
    'wallet.virtual': 'Виртуальный Торговый Портфель',
    'trading.spot': 'Спот Торговля',
    'trading.futures': 'Фьючерсная Торговля',
    'trading.options': 'Опционная Торговля',
    'ai.autotrader': 'Автоматическая Торговля ИИ'
  },
  ar: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-في-1 العقل الأعلى يجعل كسب المال أسهل',
    'portfolio.total': 'إجمالي المحفظة',
    'portfolio.change': 'تغيير 24 ساعة',
    'portfolio.trades': 'الصفقات النشطة',
    'market.overview': 'نظرة عامة على السوق',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'إجراءات سريعة',
    'actions.execute': 'تنفيذ الصفقة',
    'actions.analysis': 'تحليل المحفظة',
    'actions.risk': 'تقييم المخاطر',
    'actions.alerts': 'تنبيهات السوق',
    'status.live': 'بيانات السوق المباشرة',
    'advisor.confidence': 'الثقة',
    'advisor.recommendation': 'التوصية',
    'advisor.analysis': 'تحليل الذكاء الاصطناعي',
    'advisor.detailed': 'احصل على تحليل مفصل',
    'advisor.featured': '⭐ مميز',
    'ai.communicate': 'بدء التواصل',
    'wallet.connect': 'ربط المحفظة',
    'wallet.real': 'المحفظة الحقيقية',
    'wallet.virtual': 'محفظة التداول الافتراضية',
    'trading.spot': 'التداول الفوري',
    'trading.futures': 'تداول العقود الآجلة',
    'trading.options': 'تداول الخيارات',
    'ai.autotrader': 'التداول التلقائي بالذكاء الاصطناعي'
  },
  hi: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-इन-1 सुप्रीम ब्रेन पैसा कमाना आसान बनाता है',
    'portfolio.total': 'कुल पोर्टफोलियो',
    'portfolio.change': '24 घंटे का बदलाव',
    'portfolio.trades': 'सक्रिय ट्रेड्स',
    'market.overview': 'बाजार अवलोकन',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'त्वरित कार्य',
    'actions.execute': 'ट्रेड निष्पादित करें',
    'actions.analysis': 'पोर्टफोलियो विश्लेषण',
    'actions.risk': 'जोखिम मूल्यांकन',
    'actions.alerts': 'बाजार अलर्ट',
    'status.live': 'लाइव बाजार डेटा',
    'advisor.confidence': 'विश्वास',
    'advisor.recommendation': 'सिफारिश',
    'advisor.analysis': 'AI विश्लेषण',
    'advisor.detailed': 'विस्तृत विश्लेषण प्राप्त करें',
    'advisor.featured': '⭐ फीचर्ड',
    'ai.communicate': 'संवाद शुरू करें',
    'wallet.connect': 'वॉलेट कनेक्ट करें',
    'wallet.real': 'वास्तविक पोर्टफोलियो',
    'wallet.virtual': 'वर्चुअल ट्रेडिंग पोर्टफोलियो',
    'trading.spot': 'स्पॉट ट्रेडिंग',
    'trading.futures': 'फ्यूचर्स ट्रेडिंग',
    'trading.options': 'ऑप्शन्स ट्रेडिंग',
    'ai.autotrader': 'AI ऑटो ट्रेडिंग'
  },
  th: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-ใน-1 สมองสูงสุดทำให้การหาเงินง่ายขึ้น',
    'portfolio.total': 'พอร์ตโฟลิโอรวม',
    'portfolio.change': 'การเปลี่ยนแปลง 24 ชม.',
    'portfolio.trades': 'เทรดที่ใช้งานอยู่',
    'market.overview': 'ภาพรวมตลาด',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'การดำเนินการด่วน',
    'actions.execute': 'ดำเนินการเทรด',
    'actions.analysis': 'วิเคราะห์พอร์ตโฟลิโอ',
    'actions.risk': 'ประเมินความเสี่ยง',
    'actions.alerts': 'การแจ้งเตือนตลาด',
    'status.live': 'ข้อมูลตลาดสด',
    'advisor.confidence': 'ความมั่นใจ',
    'advisor.recommendation': 'คำแนะนำ',
    'advisor.analysis': 'การวิเคราะห์ AI',
    'advisor.detailed': 'รับการวิเคราะห์โดยละเอียด',
    'advisor.featured': '⭐ แนะนำ',
    'ai.communicate': 'เริ่มการสื่อสาร',
    'wallet.connect': 'เชื่อมต่อกระเป๋าเงิน',
    'wallet.real': 'พอร์ตโฟลิโอจริง',
    'wallet.virtual': 'พอร์ตโฟลิโอเทรดเสมือน',
    'trading.spot': 'เทรดสปอต',
    'trading.futures': 'เทรดฟิวเจอร์ส',
    'trading.options': 'เทรดออปชั่น',
    'ai.autotrader': 'เทรดอัตโนมัติ AI'
  },
  vi: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-TRONG-1 Bộ Não Tối Thượng Làm Kiếm Tiền Dễ Dàng Hơn',
    'portfolio.total': 'Tổng Danh Mục Đầu Tư',
    'portfolio.change': 'Thay Đổi 24h',
    'portfolio.trades': 'Giao Dịch Đang Hoạt Động',
    'market.overview': 'Tổng Quan Thị Trường',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Hành Động Nhanh',
    'actions.execute': 'Thực Hiện Giao Dịch',
    'actions.analysis': 'Phân Tích Danh Mục',
    'actions.risk': 'Đánh Giá Rủi Ro',
    'actions.alerts': 'Cảnh Báo Thị Trường',
    'status.live': 'Dữ Liệu Thị Trường Trực Tiếp',
    'advisor.confidence': 'Tin Tưởng',
    'advisor.recommendation': 'Khuyến Nghị',
    'advisor.analysis': 'Phân Tích AI',
    'advisor.detailed': 'Nhận Phân Tích Chi Tiết',
    'advisor.featured': '⭐ Nổi Bật',
    'ai.communicate': 'Bắt Đầu Giao Tiếp',
    'wallet.connect': 'Kết Nối Ví',
    'wallet.real': 'Danh Mục Thực',
    'wallet.virtual': 'Danh Mục Giao Dịch Ảo',
    'trading.spot': 'Giao Dịch Spot',
    'trading.futures': 'Giao Dịch Futures',
    'trading.options': 'Giao Dịch Options',
    'ai.autotrader': 'Giao Dịch Tự Động AI'
  },
  tr: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-IN-1 Yüce Beyin Para Kazanmayı Daha Kolay Hale Getirir',
    'portfolio.total': 'Toplam Portföy',
    'portfolio.change': '24s Değişim',
    'portfolio.trades': 'Aktif İşlemler',
    'market.overview': 'Pazar Genel Bakış',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Hızlı Eylemler',
    'actions.execute': 'İşlem Gerçekleştir',
    'actions.analysis': 'Portföy Analizi',
    'actions.risk': 'Risk Değerlendirmesi',
    'actions.alerts': 'Pazar Uyarıları',
    'status.live': 'Canlı Pazar Verileri',
    'advisor.confidence': 'Güven',
    'advisor.recommendation': 'Öneri',
    'advisor.analysis': 'AI Analizi',
    'advisor.detailed': 'Detaylı Analiz Al',
    'advisor.featured': '⭐ Öne Çıkan',
    'ai.communicate': 'İletişim Başlat',
    'wallet.connect': 'Cüzdan Bağla',
    'wallet.real': 'Gerçek Portföy',
    'wallet.virtual': 'Sanal İşlem Portföyü',
    'trading.spot': 'Spot İşlem',
    'trading.futures': 'Vadeli İşlem',
    'trading.options': 'Opsiyon İşlemi',
    'ai.autotrader': 'AI Otomatik İşlem'
  },
  nl: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-IN-1 Opperste Brein Maakt Geld Verdienen Makkelijker',
    'portfolio.total': 'Totale Portfolio',
    'portfolio.change': '24u Verandering',
    'portfolio.trades': 'Actieve Trades',
    'market.overview': 'Marktoverzicht',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Snelle Acties',
    'actions.execute': 'Trade Uitvoeren',
    'actions.analysis': 'Portfolio Analyse',
    'actions.risk': 'Risicobeoordeling',
    'actions.alerts': 'Marktwaarschuwingen',
    'status.live': 'Live Marktgegevens',
    'advisor.confidence': 'Vertrouwen',
    'advisor.recommendation': 'Aanbeveling',
    'advisor.analysis': 'AI Analyse',
    'advisor.detailed': 'Krijg Gedetailleerde Analyse',
    'advisor.featured': '⭐ Aanbevolen',
    'ai.communicate': 'Start Communicatie',
    'wallet.connect': 'Portemonnee Verbinden',
    'wallet.real': 'Echte Portfolio',
    'wallet.virtual': 'Virtuele Trading Portfolio',
    'trading.spot': 'Spot Trading',
    'trading.futures': 'Futures Trading',
    'trading.options': 'Opties Trading',
    'ai.autotrader': 'AI Auto Trading'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};