import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh' | 'es' | 'ja' | 'ko' | 'fr' | 'de' | 'it' | 'pt' | 'ru' | 'ar' | 'hi' | 'th' | 'vi' | 'tr' | 'nl';

interface LanguageContextType {
  language: Language;
  currentLanguage: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

// Create the context with a default value
const LanguageContext = createContext<LanguageContextType>({
  language: 'zh',
  currentLanguage: 'zh',
  setLanguage: () => {},
  t: (key: string) => key,
});

// Base English translations - all other languages will extend from this
const baseTranslations = {
  // App general
  'app.title': 'Meta BrainX',
  'app.subtitle': 'Ultimate Brain Makes Earning Money Easier',
  
  // Portfolio
  'portfolio.total': 'Total Portfolio',
  'portfolio.change': '24h Change',
  'portfolio.trades': 'Active Trades',
  'portfolio.ai_virtual': 'AI Virtual Portfolio',
  'portfolio.total_value': 'Total Value',
  'portfolio.daily_change': '24H Change',
  'portfolio.profit_loss': 'Profit/Loss Amount',
  'portfolio.active_trades': 'Active Trades',
  'portfolio.current_holdings': 'Current Holdings',
  'portfolio.no_trades': 'No Trades',
  'portfolio.simulated_trading': 'Simulated Trading',
  'portfolio.real_time_sync': 'Real-time Sync',
  'portfolio.real_time': 'Real-time',
  'portfolio.currently_trading': 'Currently Trading',
  
  // Market
  'market.overview': 'Market Overview',
  
  // AI
  'ai.advisors': 'SUPREME BRAIN',
  'ai.communicate': 'Start Communication',
  'ai.title': 'SUPREME BRAIN - Advanced Trading Analytics',
  'ai.live_analytics': 'Live Analytics',
  'ai.analysis_chat': 'AI Analysis Chat',
  'ai.ask_analysis': 'Ask for analysis on selected crypto with live market data',
  'ai.try_asking': '💡 Try asking:',
  'ai.ask_placeholder': 'Ask about technical analysis...',
  'ai.technical_analysis': 'Technical Analysis',
  'ai.news_sentiment': 'News Sentiment',
  'ai.news_sentiment_analysis': 'AI News Sentiment Analysis',
  'ai.price_chart': 'Price Chart',
  'ai.currency_selection': 'Currency Selection & Analysis',
  'ai.supreme_brain_detection': 'Supreme Brain Auto Detection',
  'ai.six_models_analysis': 'Six top AI models collaborate to analyze, only alert you for optimal trading opportunities when win rate reaches 90%+',
  'ai.start_monitoring': 'Start Monitoring',
  'ai.pause_monitoring': 'Pause Monitoring',
  'ai.monitoring': 'Monitoring...',
  'ai.paused': 'Paused',
  'ai.clear_history': 'Clear History',
  'ai.detection_history': 'Detection History',
  'ai.records': 'Records',
  'ai.no_records_monitoring': 'Monitoring in progress, waiting for high probability opportunities...',
  'ai.no_records_start': 'No detection records yet, please start monitoring',
  'ai.last_check': 'Last Check',
  'ai.monitoring_started': 'Supreme Brain Detection Started',
  'ai.monitoring_started_desc': 'System will automatically analyze market opportunities every 30 seconds',
  'ai.monitoring_paused': 'Supreme Brain Detection Paused',
  'ai.monitoring_paused_desc': 'Stopped automatic analysis',
  'ai.all_alerts_cleared': 'All Alerts Cleared',
  'ai.history_cleared': 'Historical alert records have been cleared',
  'ai.high_probability_opportunity': 'Supreme Brain Detected High Probability Opportunity!',
  'ai.buy_signal': 'Buy Signal',
  'ai.sell_signal': 'Sell Signal', 
  'ai.win_rate': 'Win Rate',
  'ai.price_analysis': 'Price Analysis',
  'ai.technical_indicators': 'Technical Indicators',
  'ai.news_analysis': 'News Analysis',
  'ai.got_it': 'Got It',
  'ai.trade_now': 'Trade Now',
  'ai.kline_chart': 'K-line Chart & Technical Indicators',
  'ai.professional_kline': 'Professional K-line Chart',
  'ai.realtime_data': 'Real-time Price Data + Technical Indicator Overlay',
  'ai.technical_panel': 'Technical Indicators Panel',
  'ai.basic_indicators': 'Basic Indicators',
  'ai.moving_averages': 'Moving Averages',
  
  // AI Control Center
  'ai.control_center.title': 'AI Control Center',
  'ai.control_center.description': 'Configure and manage your AI trading assistants',
  'ai.control_center.system_status': 'System Status Overview',
  'ai.control_center.elon_config': 'Elon Musk Configuration',
  'ai.control_center.elon_desc': 'Tesla founder focusing on market sentiment analysis and innovative investment strategies',
  'ai.control_center.warren_config': 'Warren Buffett Configuration',
  'ai.control_center.warren_desc': 'Investment master focusing on value analysis and long-term investment strategies',
  'ai.control_center.bill_config': 'Bill Gates Configuration', 
  'ai.control_center.bill_desc': 'Technology giant focusing on quantitative analysis and data-driven investment decisions',
  'ai.control_center.vitalik_config': 'Vitalik Buterin Configuration',
  'ai.control_center.vitalik_desc': 'Ethereum founder focusing on blockchain technology and cryptocurrency market analysis',
  'ai.control_center.trump_config': 'Donald Trump Configuration',
  'ai.control_center.trump_desc': 'Business mogul focusing on economic policy analysis and market trend prediction',
  'ai.control_center.justin_config': 'Justin Sun Configuration',
  'ai.control_center.justin_desc': 'TRON founder focusing on market momentum analysis and short-term trading opportunities',
  
  // Status
  'status.live': 'Real-time Market Data',
  
  // Actions
  'actions.title': 'Quick Actions',
  'actions.execute': 'Execute Trade',
  'actions.analysis': 'Portfolio Analysis',
  'actions.risk': 'Risk Assessment',
  'actions.alerts': 'Market Alerts',
  
  // Advisor
  'advisor.confidence': 'Confident',
  'advisor.recommendation': 'Recommendation',
  'advisor.analysis': 'AI Analysis',
  'advisor.detailed': 'Get Detailed Analysis',
  'advisor.featured': '⭐ Featured',
  
  // Wallet
  'wallet.connect': 'Connect Wallet',
  'wallet.real': 'Real Wallet',
  'wallet.virtual': 'AI Virtual Portfolio',
  'wallet.ai_virtual_badge': 'AI Virtual',
  'wallet.connect_wallet': 'Connect Wallet',
  'wallet.multiple_options': 'Multiple Options',
  'wallet.connected': 'Connected',
  'wallet.address_short': 'Wallet Address',
  'wallet.connect_title': 'Connect Wallet',
  'wallet.select_description': 'Choose the most secure and reliable wallet to start trading and managing your portfolio',
  'wallet.address': 'Wallet Address:',
  'wallet.network': 'Network:',
  'wallet.view_explorer': 'View in Block Explorer',
  'wallet.disconnect': 'Disconnect',
  'wallet.connection_success': 'Wallet Connected',
  'wallet.connection_success_desc': 'Successfully connected to {wallet}',
  'wallet.connection_failed': 'Connection Failed',
  'wallet.connection_failed_desc': 'Failed to connect wallet. Please try again.',
  'wallet.disconnected': 'Wallet Disconnected',
  'wallet.disconnected_desc': 'Your wallet has been disconnected.',
  'wallet.address_copied': 'Address Copied',
  'wallet.address_copied_desc': 'Wallet address has been copied to clipboard.',
  
  // Trading
  'trading.spot': 'Spot Trading',
  'trading.futures': 'Futures Trading',
  'trading.options': 'Options Trading',
  'trading.strategy': 'Trading Strategy',
  'trading.type': 'Trading Type',
  'trading.leverage': 'Leverage',
  
  // Buttons
  'button.refresh': 'Refresh Data',
  'button.show_top': 'Show Top 6',
  'button.all_categories': 'All Categories',
  'button.collapse': 'Collapse',
  'button.view_all': 'View All',
  
  // Search
  'search.placeholder': 'Search cryptocurrencies (e.g.: Bitcoin, BTC)...',
  'search.clear': 'Clear Search',
  'search.showing': 'Showing',
  'search.of': '/',
  'search.currencies': 'cryptocurrencies',
  'search.filter': 'Search',
  'search.not_found': 'No cryptocurrencies found matching',
  'search.try_other': '',
  'search.suggestion': 'Please try searching with other keywords like Bitcoin, BTC',
  
  // Language
  'language.switch': 'Language Switch',
  
  // Profile
  'profile.personal': 'Personal Profile',
  'profile.settings': 'Profile Settings',
  'profile.edit': 'Edit Profile',
  'profile.click_edit': 'Click to Edit',
  'profile.saved': 'Profile Saved',
  'profile.updated': 'Your avatar and name have been successfully updated',
  
  // Auth
  'auth.login': 'Login',
  'auth.register': 'Register', 
  'auth.login_register': 'Login / Register',
  'auth.logout': 'Logout',
  'auth.loading': 'Loading...',
  
  // AI Advisors - Individual profiles
  'advisors.elon.specialty': 'Visionary Technology & Market Disruption',
  'advisors.elon.investment_style': 'Disruptive Innovation',
  'advisors.elon.quote': 'When others are cautious, be bold; when others are bold, be cautious.',
  'advisors.elon.achievement1': 'SpaceX CEO',
  'advisors.elon.achievement2': 'Tesla Founder',
  'advisors.elon.achievement3': 'Richest Person',
  'advisors.elon.achievement4': 'Reusable Rocket Technology',
  'advisors.elon.tag1': 'Mars Colonization',
  'advisors.elon.tag2': 'Electric Vehicles',
  'advisors.elon.tag3': 'AI',
  
  'advisors.warren.specialty': 'Value Investing & Long-term Wealth Building',
  'advisors.warren.investment_style': 'Value Investing',
  'advisors.warren.quote': 'Be fearful when others are greedy, and greedy when others are fearful.',
  'advisors.warren.achievement1': 'Berkshire CEO',
  'advisors.warren.achievement2': 'Investment Guru',
  'advisors.warren.achievement3': 'Philanthropist',
  'advisors.warren.achievement4': 'Oracle of Omaha',
  'advisors.warren.tag1': 'Value Investing',
  'advisors.warren.tag2': 'Long-term Holding',
  'advisors.warren.tag3': 'Fundamentals',
  
  'advisors.bill.specialty': 'Technology Innovation & Philanthropic Investment',
  'advisors.bill.investment_style': 'Tech Innovation',
  'advisors.bill.quote': 'Success is a lousy teacher. It seduces smart people into thinking they can\'t lose.',
  'advisors.bill.achievement1': 'Microsoft Founder',
  'advisors.bill.achievement2': 'Gates Foundation',
  'advisors.bill.achievement3': 'Philanthropy',
  'advisors.bill.achievement4': 'Global Health Advocate',
  'advisors.bill.holding3': 'Clean Energy',
  'advisors.bill.tag1': 'Philanthropy',
  'advisors.bill.tag2': 'Health',
  'advisors.bill.tag3': 'Education',
  
  'advisors.vitalik.specialty': 'Blockchain & Decentralization',
  'advisors.vitalik.investment_style': 'Decentralized Future',
  'advisors.vitalik.quote': 'Blockchain is not just a financial revolution, but a new paradigm for decentralized coordination.',
  'advisors.vitalik.achievement1': 'Ethereum Co-founder',
  'advisors.vitalik.achievement2': 'Smart Contract Pioneer',
  'advisors.vitalik.achievement3': 'Blockchain Evangelist',
  'advisors.vitalik.achievement4': 'Crypto Punk Leader',
  'advisors.vitalik.holding2': 'Various DeFi Tokens',
  'advisors.vitalik.holding3': 'Public Goods Fund',
  'advisors.vitalik.tag1': 'Smart Contracts',
  'advisors.vitalik.tag2': 'DeFi',
  'advisors.vitalik.tag3': 'Web3',
  
  'advisors.justin.specialty': 'TRON Ecosystem & Marketing',
  'advisors.justin.investment_style': 'Marketing-Driven Growth',
  'advisors.justin.quote': 'In the crypto world, marketing and technology are equally important.',
  'advisors.justin.achievement1': 'TRON Founder',
  'advisors.justin.achievement2': 'Huobi Global Advisory',
  'advisors.justin.achievement3': 'Expensive NFT Collector',
  'advisors.justin.achievement4': 'Crypto Marketing Master',
  'advisors.justin.holding4': 'NFT Collection',
  'advisors.justin.tag1': 'TRON',
  'advisors.justin.tag2': 'Marketing',
  'advisors.justin.tag3': 'DeFi',
  
  'advisors.trump.specialty': 'Real Estate & Brand Investment',
  'advisors.trump.investment_style': 'Brand Value Driven',
  'advisors.trump.quote': 'We\'re going to make America great again, make investments great again!',
  'advisors.trump.achievement1': 'Trump Organization Chairman',
  'advisors.trump.achievement2': '45th US President',
  'advisors.trump.achievement3': 'Real Estate Mogul',
  'advisors.trump.achievement4': 'Brand Licensing Expert',
  'advisors.trump.holding1': 'Real Estate',
  'advisors.trump.holding2': 'Trump NFTs',
  'advisors.trump.holding3': 'Gold',
  'advisors.trump.tag1': 'Real Estate',
  'advisors.trump.tag2': 'Branding',
  'advisors.trump.tag3': 'Politics',
  
  // Auto trader
  'autotrader.button': 'AI Auto Money',
  'autotrader.title': 'AI Auto Money System - Multi-Model Smart Trading',
  
  // Crypto
  'crypto.volume24h': '24h Volume',
  'crypto.marketCap': 'Market Cap',
  'crypto.circulatingSupply': 'Circulating Supply',
  'crypto.marketRank': 'Market Rank',
  'crypto.marketDominance': 'Market Dominance',
  'crypto.maxSupply': 'Max Supply',
  'crypto.supplyRatio': 'Supply Ratio',

  // Advisors main
  'advisors.more_models': 'More Models',
  'advisors.not_alone': 'You Are Not Alone',
  'advisors.coming_soon': 'Coming Soon',
  'advisors.coming_soon_status': 'Coming Soon',
  
  // Individual advisor names and details
  'advisors.trump.name': 'Donald Trump',
  'advisors.trump.status': 'Available',
  'advisors.quantitative.name': 'Quantitative Master',
  'advisors.quantitative.specialty': 'Quantitative Analysis & Algorithmic Trading',
  'advisors.quantitative.expertise': 'Quant Analysis',
  'advisors.crypto.name': 'Crypto Specialist',
  'advisors.crypto.specialty': 'Cryptocurrency Market Analysis',
  'advisors.crypto.expertise': 'Crypto Trading',
  'advisors.macro.name': 'Macro Economist',
  'advisors.macro.specialty': 'Macroeconomic Analysis & Global Markets',
  'advisors.macro.expertise': 'Macro Strategy',
  
  // Upcoming advisors details
  'upcoming.description.trump': 'Real estate mogul and business leader with decades of investment experience',
  'upcoming.description.quant': 'Advanced quantitative analysis using mathematical models and algorithms',
  'upcoming.description.crypto': 'Specialized in cryptocurrency market dynamics and blockchain technology',
  'upcoming.description.macro': 'Expert in global economic trends and macroeconomic policy analysis',
  
  'upcoming.title.trump': 'Business Mogul & Investment Strategist',
  'upcoming.title.quant': 'Quantitative Analysis Expert',
  'upcoming.title.crypto': 'Cryptocurrency Market Specialist',
  'upcoming.title.macro': 'Global Macro Economist',
  
  'upcoming.achievements.trump.1': 'Trump Organization Chairman',
  'upcoming.achievements.trump.2': '45th President of the United States',
  'upcoming.achievements.trump.3': 'Real Estate Development Empire',
  'upcoming.achievements.trump.4': 'Brand Licensing & Media Success',
  'upcoming.achievements.tbd': 'To Be Announced',
  
  'upcoming.specialty.trump': 'Real Estate Investment, Brand Building, and Strategic Asset Management',
  'upcoming.specialty.quant': 'Mathematical Models, Statistical Analysis, and Algorithmic Trading Systems',
  'upcoming.specialty.crypto': 'Blockchain Technology, DeFi Protocols, and Cryptocurrency Market Analysis',
  'upcoming.specialty.macro': 'Global Economic Policy, Interest Rate Analysis, and Currency Markets',
  
  'upcoming.experience.trump': '40+ Years in Business',
  'upcoming.experience.quant': 'Advanced Analytics',
  'upcoming.experience.crypto': 'Blockchain Innovation',
  'upcoming.experience.macro': 'Global Economics',
  
  'upcoming.philosophy.trump': 'Make deals that create lasting value and build strong brands',
  'upcoming.philosophy.quant': 'Data-driven decisions eliminate emotion from trading',
  'upcoming.philosophy.crypto': 'Decentralization is the future of finance',
  'upcoming.philosophy.macro': 'Global economic cycles drive all market movements',
  
  'upcoming.skills.trump.1': 'Real Estate',
  'upcoming.skills.trump.2': 'Branding',
  'upcoming.skills.trump.3': 'Negotiation',
  'upcoming.skills.trump.4': 'Media Strategy',
  
  'upcoming.key.achievements': 'Key Achievements',
  'upcoming.specialty': 'Specialty',
  'upcoming.philosophy': 'Investment Philosophy',
  'upcoming.core.skills': 'Core Skills',
  'upcoming.experience': 'Experience',
  'upcoming.elite.assembling': 'Elite Assembling'
};

const translations = {
  en: baseTranslations,
  
  zh: {
    ...baseTranslations,
    'app.subtitle': '终极大脑让赚钱更简单',
    'portfolio.total': '总投资组合',
    'portfolio.change': '24小时变化',
    'portfolio.trades': '活跃交易',
    'portfolio.ai_virtual': 'AI虚拟投资组合',
    'portfolio.total_value': '总价值',
    'portfolio.daily_change': '日变化',
    'portfolio.profit_loss': '盈亏金额',
    'portfolio.active_trades': '活跃交易',
    'portfolio.current_holdings': '当前持仓',
    'portfolio.no_trades': '无交易',
    'portfolio.simulated_trading': '模拟交易',
    'portfolio.real_time_sync': '实时同步',
    'portfolio.real_time': '实时',
    'portfolio.currently_trading': '正在交易',
    'market.overview': '市场概览',
    'ai.communicate': '开始沟通',
    'ai.title': 'SUPREME BRAIN - 高级交易分析',
    'ai.live_analytics': '实时分析',
    'ai.analysis_chat': 'AI分析聊天',
    'ai.ask_analysis': '使用实时市场数据询问所选加密货币的分析',
    'ai.try_asking': '💡 尝试询问:',
    'ai.ask_placeholder': '询问技术分析...',
    'ai.technical_analysis': '技术分析',
    'ai.news_sentiment': '新闻情绪',
    'ai.news_sentiment_analysis': 'AI新闻情绪分析',
    'ai.price_chart': '价格图表',
    'ai.currency_selection': '货币选择与分析',
    'ai.supreme_brain_detection': '最强大脑自动检测',
    'ai.six_models_analysis': '六个顶级AI模型协同分析，只在胜率达到90%以上时提醒您最佳交易时机',
    'ai.start_monitoring': '开始监控',
    'ai.pause_monitoring': '暂停监控',
    'ai.monitoring': '监控中...',
    'ai.paused': '已暂停',
    'ai.clear_history': '清除历史',
    'ai.detection_history': '检测历史',
    'ai.records': '条记录',
    'ai.no_records_monitoring': '监控进行中，等待高概率机会...',
    'ai.no_records_start': '暂无检测记录，请开始监控',
    'ai.last_check': '最后检查',
    'ai.monitoring_started': '最强大脑检测已启动',
    'ai.monitoring_started_desc': '系统将每30秒自动分析市场机会',
    'ai.monitoring_paused': '最强大脑检测已暂停',
    'ai.monitoring_paused_desc': '已停止自动分析',
    'ai.all_alerts_cleared': '所有提醒已清除',
    'ai.history_cleared': '历史提醒记录已清除',
    'ai.high_probability_opportunity': '最强大脑检测到高概率机会！',
    'ai.buy_signal': '买入信号',
    'ai.sell_signal': '卖出信号',
    'ai.win_rate': '胜率',
    'ai.price_analysis': '价格分析',
    'ai.technical_indicators': '技术指标',
    'ai.news_analysis': '新闻分析',
    'ai.got_it': '知道了',
    'ai.trade_now': '立即交易',
    'ai.kline_chart': 'K线图表与技术指标',
    'ai.professional_kline': '专业K线图表',
    'ai.realtime_data': '实时价格数据 + 技术指标叠加',
    'ai.technical_panel': '技术指标面板',
    'ai.basic_indicators': '基础指标',
    'ai.moving_averages': '移动平均线',
    'status.live': '实时市场数据',
    'actions.title': '快速操作',
    'actions.execute': '执行交易',
    'actions.analysis': '投资组合分析',
    'actions.risk': '风险评估',
    'actions.alerts': '市场提醒',
    'advisor.confidence': '置信度',
    'advisor.recommendation': '推荐',
    'advisor.analysis': 'AI分析',
    'advisor.detailed': '获取详细分析',
    'advisor.featured': '⭐ 精选',
    'wallet.connect': '连接钱包',
    'wallet.real': '真实钱包',
    'wallet.virtual': 'AI虚拟投资组合',
    'wallet.ai_virtual_badge': 'AI虚拟',
    'wallet.connect_wallet': '连接钱包',
    'wallet.multiple_options': '多种选择',
    'wallet.connected': '已连接',
    'wallet.address_short': '钱包地址',
    'wallet.connect_title': '连接钱包',
    'wallet.select_description': '选择最安全可靠的钱包开始交易和管理您的投资组合',
    'wallet.address': '钱包地址：',
    'wallet.network': '网络：',
    'wallet.view_explorer': '在区块浏览器中查看',
    'wallet.disconnect': '断开连接',
    'wallet.connection_success': '钱包已连接',
    'wallet.connection_success_desc': '成功连接到 {wallet}',
    'wallet.connection_failed': '连接失败',
    'wallet.connection_failed_desc': '连接钱包失败，请重试。',
    'wallet.disconnected': '钱包已断开',
    'wallet.disconnected_desc': '您的钱包已断开连接。',
    'wallet.address_copied': '地址已复制',
    'wallet.address_copied_desc': '钱包地址已复制到剪贴板。',
    'trading.spot': '现货交易',
    'trading.futures': '期货交易',
    'trading.options': '期权交易',
    'trading.strategy': '交易策略',
    'trading.type': '交易类型',
    'trading.leverage': '杠杆',
    'button.refresh': '刷新数据',
    'button.show_top': '显示前6名',
    'button.all_categories': '所有类别',
    'button.collapse': '收起',
    'button.view_all': '查看全部',
    'search.placeholder': '搜索加密货币 (例如: Bitcoin, BTC)...',
    'search.clear': '清除搜索',
    'search.showing': '显示',
    'search.of': '/',
    'search.currencies': '种加密货币',
    'search.filter': '搜索',
    'search.not_found': '未找到匹配的加密货币',
    'search.try_other': '',
    'search.suggestion': '请尝试使用其他关键词搜索，如Bitcoin、BTC',
    'language.switch': '语言切换',
    'profile.personal': '个人资料',
    'profile.settings': '个人设置',
    'profile.edit': '编辑资料',
    'profile.click_edit': '点击编辑',
    'profile.saved': '资料已保存',
    'profile.updated': '您的头像和姓名已成功更新',
    'auth.login': '登录',
    'auth.register': '注册',
    'auth.login_register': '登录 / 注册',
    'auth.logout': '退出登录',
    'auth.loading': '加载中...',
    'advisors.elon.specialty': '远见科技与市场颠覆',
    'advisors.elon.investment_style': '颠覆性创新',
    'advisors.elon.quote': '当其他人都谨慎时，要大胆；当其他人都大胆时，要谨慎。',
    'advisors.elon.achievement1': 'SpaceX CEO',
    'advisors.elon.achievement2': 'Tesla创始人',
    'advisors.elon.achievement3': '世界首富',
    'advisors.elon.achievement4': '可重复火箭技术',
    'advisors.elon.tag1': '火星殖民',
    'advisors.elon.tag2': '电动汽车',
    'advisors.elon.tag3': 'AI',
    'advisors.warren.specialty': '价值投资与长期财富建设',
    'advisors.warren.investment_style': '价值投资',
    'advisors.warren.quote': '在别人贪婪时恐惧，在别人恐惧时贪婪。',
    'advisors.warren.achievement1': '伯克希尔CEO',
    'advisors.warren.achievement2': '投资教父',
    'advisors.warren.achievement3': '慈善家',
    'advisors.warren.achievement4': '奥马哈先知',
    'advisors.warren.tag1': '价值投资',
    'advisors.warren.tag2': '长期持有',
    'advisors.warren.tag3': '基本面',
    'advisors.bill.specialty': '科技创新与慈善投资',
    'advisors.bill.investment_style': '科技创新',
    'advisors.bill.quote': '成功是一个糟糕的老师，它会让聪明人觉得自己不会失败。',
    'advisors.bill.achievement1': '微软创始人',
    'advisors.bill.achievement2': '盖茨基金会',
    'advisors.bill.achievement3': '慈善事业',
    'advisors.bill.achievement4': '全球健康倡导者',
    'advisors.bill.holding3': '清洁能源',
    'advisors.bill.tag1': '慈善',
    'advisors.bill.tag2': '健康',
    'advisors.bill.tag3': '教育',
    'advisors.vitalik.specialty': '区块链与去中心化',
    'advisors.vitalik.investment_style': '去中心化未来',
    'advisors.vitalik.quote': '区块链不仅仅是金融革命，更是去中心化协调的新范式。',
    'advisors.vitalik.achievement1': '以太坊联合创始人',
    'advisors.vitalik.achievement2': '智能合约先驱',
    'advisors.vitalik.achievement3': '区块链布道者',
    'advisors.vitalik.achievement4': '加密朋克精神领袖',
    'advisors.vitalik.holding2': '各类DeFi代币',
    'advisors.vitalik.holding3': '公共物品基金',
    'advisors.vitalik.tag1': '智能合约',
    'advisors.vitalik.tag2': 'DeFi',
    'advisors.vitalik.tag3': 'Web3',
    'advisors.justin.specialty': 'TRON生态与营销',
    'advisors.justin.investment_style': '营销驱动增长',
    'advisors.justin.quote': '在加密货币世界中，营销和技术同样重要。',
    'advisors.justin.achievement1': 'TRON创始人',
    'advisors.justin.achievement2': '火币全球顾问委员会',
    'advisors.justin.achievement3': '天价NFT收藏家',
    'advisors.justin.achievement4': '加密营销大师',
    'advisors.justin.holding4': 'NFT收藏',
    'advisors.justin.tag1': 'TRON',
    'advisors.justin.tag2': '营销',
    'advisors.justin.tag3': 'DeFi',
    'advisors.trump.specialty': '房地产与品牌投资',
    'advisors.trump.investment_style': '品牌价值驱动',
    'advisors.trump.quote': '我们要让美国再次伟大，让投资再次伟大！',
    'advisors.trump.achievement1': '特朗普集团主席',
    'advisors.trump.achievement2': '美国第45任总统',
    'advisors.trump.achievement3': '房地产大亨',
    'advisors.trump.achievement4': '品牌授权专家',
    'advisors.trump.holding1': '房地产',
    'advisors.trump.holding2': '特朗普NFT',
    'advisors.trump.holding3': '黄金',
    'advisors.trump.tag1': '房地产',
    'advisors.trump.tag2': '品牌',
    'advisors.trump.tag3': '政治',
    'autotrader.button': 'AI自动赚钱',
    'autotrader.title': 'AI自动赚钱系统 - 多模型智能交易',
    'crypto.volume24h': '24小时交易量',
    'crypto.marketCap': '市值',
    'crypto.circulatingSupply': '流通供应量',
    'crypto.marketRank': '市场排名',
    'crypto.marketDominance': '市场主导地位',
    'crypto.maxSupply': '最大供应量',
    'crypto.supplyRatio': '供应比率',

    // Advisors main
    'advisors.more_models': '更多模型',
    'advisors.not_alone': '您并不孤单',
    'advisors.coming_soon': '即将推出',
    'advisors.coming_soon_status': '即将推出',
    
    // Individual advisor names and details
    'advisors.trump.name': '唐纳德·特朗普',
    'advisors.trump.status': '可用',
    'advisors.quantitative.name': '量化大师',
    'advisors.quantitative.specialty': '量化分析与算法交易',
    'advisors.quantitative.expertise': '量化分析',
    'advisors.crypto.name': '加密货币专家',
    'advisors.crypto.specialty': '加密货币市场分析',
    'advisors.crypto.expertise': '加密交易',
    'advisors.macro.name': '宏观经济学家',
    'advisors.macro.specialty': '宏观经济分析与全球市场',
    'advisors.macro.expertise': '宏观策略',
    
    // Upcoming advisors details
    'upcoming.description.trump': '房地产大亨和商界领袖，拥有数十年投资经验',
    'upcoming.description.quant': '使用数学模型和算法进行高级量化分析',
    'upcoming.description.crypto': '专门研究加密货币市场动态和区块链技术',
    'upcoming.description.macro': '全球经济趋势和宏观经济政策分析专家',
    
    'upcoming.title.trump': '商业大亨与投资策略师',
    'upcoming.title.quant': '量化分析专家',
    'upcoming.title.crypto': '加密货币市场专家',
    'upcoming.title.macro': '全球宏观经济学家',
    
    'upcoming.achievements.trump.1': '特朗普集团主席',
    'upcoming.achievements.trump.2': '美国第45任总统',
    'upcoming.achievements.trump.3': '房地产开发帝国',
    'upcoming.achievements.trump.4': '品牌授权与媒体成功',
    'upcoming.achievements.tbd': '待公布',
    
    'upcoming.specialty.trump': '房地产投资、品牌建设和战略资产管理',
    'upcoming.specialty.quant': '数学模型、统计分析和算法交易系统',
    'upcoming.specialty.crypto': '区块链技术、DeFi协议和加密货币市场分析',
    'upcoming.specialty.macro': '全球经济政策、利率分析和货币市场',
    
    'upcoming.experience.trump': '40+年商业经验',
    'upcoming.experience.quant': '高级分析',
    'upcoming.experience.crypto': '区块链创新',
    'upcoming.experience.macro': '全球经济学',
    
    'upcoming.philosophy.trump': '进行能创造持久价值并建立强势品牌的交易',
    'upcoming.philosophy.quant': '数据驱动的决策消除交易中的情绪因素',
    'upcoming.philosophy.crypto': '去中心化是金融的未来',
    'upcoming.philosophy.macro': '全球经济周期驱动所有市场走势',
    
    'upcoming.skills.trump.1': '房地产',
    'upcoming.skills.trump.2': '品牌建设',
    'upcoming.skills.trump.3': '谈判',
    'upcoming.skills.trump.4': '媒体策略',
    
    'upcoming.key.achievements': '主要成就',
    'upcoming.specialty': '专业领域',
    'upcoming.philosophy': '投资理念',
    'upcoming.core.skills': '核心技能',
    'upcoming.experience': '经验',
    'upcoming.elite.assembling': '精英组装中'
  },
  
  ja: {
    ...baseTranslations,
    'app.subtitle': '究極の頭脳でお金を稼ぐのが簡単になる',
    'portfolio.total': '総ポートフォリオ',
    'portfolio.change': '24時間変動',
    'portfolio.trades': 'アクティブトレード',
    'market.overview': '市場概要',
    'ai.communicate': 'コミュニケーション開始',
    'status.live': 'リアルタイム市場データ',
    'advisor.confidence': '信頼度',
    'advisor.recommendation': '推奨',
    'advisor.analysis': 'AI分析',
    'advisor.detailed': '詳細分析を取得',
    'advisor.featured': '⭐ 注目',
    'wallet.connect': 'ウォレット接続',
    'trading.strategy': '取引戦略',
    'button.refresh': 'データ更新',
    'button.all_categories': '全カテゴリ',
    'search.placeholder': '暗号通貨を検索 (例: Bitcoin, BTC)...',
    'language.switch': '言語切替',
    'auth.login': 'ログイン',
    'auth.register': '登録',
    'autotrader.button': 'AI自動マネー',
    'advisors.elon.specialty': 'ビジョナリーテクノロジー＆市場破壊',
    'advisors.warren.specialty': 'バリュー投資＆長期資産構築',
    'advisors.bill.specialty': 'テクノロジー革新＆慈善投資',
    'advisors.vitalik.specialty': 'ブロックチェーン＆分散化',
    'advisors.justin.specialty': 'TRONエコシステム＆マーケティング',
    'advisors.trump.specialty': '不動産＆ブランド投資',
    
    // Missing keys for Japanese
    'advisors.more_models': 'より多くのモデル',
    'advisors.not_alone': 'あなたは一人ではありません',
    'advisors.coming_soon': '近日公開',
    'advisors.coming_soon_status': '近日公開',
    'advisors.trump.name': 'ドナルド・トランプ',
    'advisors.trump.status': '利用可能',
    'advisors.quantitative.name': 'クオンツマスター',
    'advisors.quantitative.specialty': 'クオンツ分析とアルゴリズム取引',
    'advisors.quantitative.expertise': 'クオンツ分析',
     'advisors.crypto.name': '暗号通貨専門家',
    'advisors.crypto.specialty': '暗号通貨市場分析',
    'advisors.crypto.expertise': '暗号取引',
    'advisors.macro.name': 'マクロ経済学者',
    'advisors.macro.specialty': 'マクロ経済分析とグローバル市場',
    'advisors.macro.expertise': 'マクロ戦略',
    'upcoming.description.trump': '数十年の投資経験を持つ不動産王と経営者',
    'upcoming.elite.assembling': 'エリート集結中'
  },
  
  ko: {
    ...baseTranslations,
    'app.subtitle': '궁극의 두뇌로 돈 버는 게 쉬워진다',
    'portfolio.total': '총 포트폴리오',
    'portfolio.change': '24시간 변동',
    'portfolio.trades': '활성 거래',
    'market.overview': '시장 개요',
    'ai.communicate': '소통 시작',
    'status.live': '실시간 시장 데이터',
    'advisor.confidence': '신뢰도',
    'advisor.recommendation': '추천',
    'advisor.analysis': 'AI 분석',
    'advisor.detailed': '상세 분석 받기',
    'advisor.featured': '⭐ 추천',
    'wallet.connect': '지갑 연결',
    'trading.strategy': '거래 전략',
    'button.refresh': '데이터 새로고침',
    'button.all_categories': '모든 카테고리',
    'search.placeholder': '암호화폐 검색 (예: Bitcoin, BTC)...',
    'language.switch': '언어 전환',
    'auth.login': '로그인',
    'auth.register': '회원가입',
    'autotrader.button': 'AI 자동 머니',
    'advisors.elon.specialty': '비전 기술 & 시장 혁신',
    'advisors.warren.specialty': '가치 투자 & 장기 자산 구축',
    'advisors.bill.specialty': '기술 혁신 & 자선 투자',
    'advisors.vitalik.specialty': '블록체인 & 탈중앙화',
    'advisors.justin.specialty': 'TRON 생태계 & 마케팅',
    'advisors.trump.specialty': '부동산 & 브랜드 투자',
    
    // Missing keys for Korean
    'advisors.more_models': '더 많은 모델',
    'advisors.not_alone': '당신은 혼자가 아닙니다',
    'advisors.coming_soon': '곧 출시',
    'advisors.coming_soon_status': '곧 출시',
    'advisors.trump.name': '도널드 트럼프',
    'advisors.trump.status': '사용 가능',
    'advisors.quantitative.name': '퀀트 마스터',
    'advisors.quantitative.specialty': '정량 분석 및 알고리즘 거래',
    'advisors.quantitative.expertise': '퀀트 분석',
    'advisors.crypto.name': '암호화폐 전문가',
    'advisors.crypto.specialty': '암호화폐 시장 분석',
    'advisors.crypto.expertise': '암호화폐 거래',
    'advisors.macro.name': '거시경제학자',
    'advisors.macro.specialty': '거시경제 분석 및 글로벌 시장',
    'advisors.macro.expertise': '거시 전략',
    'upcoming.description.trump': '수십 년의 투자 경험을 가진 부동산 거물과 비즈니스 리더',
    'upcoming.elite.assembling': '엘리트 조립 중'
  },
  
  es: {
    ...baseTranslations,
    'app.subtitle': 'El Cerebro Definitivo Hace Que Ganar Dinero Sea Más Fácil',
    'portfolio.total': 'Portafolio Total',
    'portfolio.change': 'Cambio 24h',
    'portfolio.trades': 'Operaciones Activas',
    'market.overview': 'Resumen del Mercado',
    'ai.communicate': 'Iniciar Comunicación',
    'status.live': 'Datos de Mercado en Tiempo Real',
    'advisor.confidence': 'Confianza',
    'advisor.recommendation': 'Recomendación',
    'advisor.analysis': 'Análisis IA',
    'advisor.detailed': 'Obtener Análisis Detallado',
    'advisor.featured': '⭐ Destacado',
    'wallet.connect': 'Conectar Cartera',
    'trading.strategy': 'Estrategia de Trading',
    'button.refresh': 'Actualizar Datos',
    'button.all_categories': 'Todas las Categorías',
    'search.placeholder': 'Buscar criptomonedas (ej: Bitcoin, BTC)...',
    'language.switch': 'Cambio de Idioma',
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Registrarse',
    'autotrader.button': 'IA Auto Dinero',
    'advisors.elon.specialty': 'Tecnología Visionaria y Disrupción del Mercado',
    'advisors.warren.specialty': 'Inversión de Valor y Construcción de Riqueza a Largo Plazo',
    'advisors.bill.specialty': 'Innovación Tecnológica e Inversión Filantrópica',
    'advisors.vitalik.specialty': 'Blockchain y Descentralización',
    'advisors.justin.specialty': 'Ecosistema TRON y Marketing',
    'advisors.trump.specialty': 'Inversión Inmobiliaria y de Marca'
  },
  
  fr: {
    ...baseTranslations,
    'app.subtitle': 'Le Cerveau Ultime Rend Gagner de l\'Argent Plus Facile',
    'portfolio.total': 'Portefeuille Total',
    'portfolio.change': 'Changement 24h',
    'portfolio.trades': 'Trades Actifs',
    'market.overview': 'Aperçu du Marché',
    'ai.communicate': 'Commencer la Communication',
    'status.live': 'Données de Marché en Temps Réel',
    'advisor.confidence': 'Confiance',
    'advisor.recommendation': 'Recommandation',
    'advisor.analysis': 'Analyse IA',
    'advisor.detailed': 'Obtenir une Analyse Détaillée',
    'advisor.featured': '⭐ En Vedette',
    'wallet.connect': 'Connecter Portefeuille',
    'trading.strategy': 'Stratégie de Trading',
    'button.refresh': 'Actualiser les Données',
    'button.all_categories': 'Toutes les Catégories',
    'search.placeholder': 'Rechercher des cryptomonnaies (ex: Bitcoin, BTC)...',
    'language.switch': 'Changement de Langue',
    'auth.login': 'Se Connecter',
    'auth.register': 'S\'Inscrire',
    'autotrader.button': 'IA Auto Argent',
    'advisors.elon.specialty': 'Technologie Visionnaire et Disruption du Marché',
    'advisors.warren.specialty': 'Investissement de Valeur et Construction de Richesse à Long Terme',
    'advisors.bill.specialty': 'Innovation Technologique et Investissement Philanthropique',
    'advisors.vitalik.specialty': 'Blockchain et Décentralisation',
    'advisors.justin.specialty': 'Écosystème TRON et Marketing',
    'advisors.trump.specialty': 'Investissement Immobilier et de Marque'
  },
  
  de: {
    ...baseTranslations,
    'app.subtitle': 'Das ultimative Gehirn macht Geld verdienen einfacher',
    'portfolio.total': 'Gesamt-Portfolio',
    'portfolio.change': '24h Änderung',
    'portfolio.trades': 'Aktive Trades',
    'market.overview': 'Marktübersicht',
    'ai.communicate': 'Kommunikation starten',
    'status.live': 'Echtzeit-Marktdaten',
    'advisor.confidence': 'Vertrauen',
    'advisor.recommendation': 'Empfehlung',
    'advisor.analysis': 'KI-Analyse',
    'advisor.detailed': 'Detaillierte Analyse erhalten',
    'advisor.featured': '⭐ Empfohlen',
    'wallet.connect': 'Wallet verbinden',
    'trading.strategy': 'Trading-Strategie',
    'button.refresh': 'Daten aktualisieren',
    'button.all_categories': 'Alle Kategorien',
    'search.placeholder': 'Kryptowährungen suchen (z.B.: Bitcoin, BTC)...',
    'language.switch': 'Sprachwechsel',
    'auth.login': 'Anmelden',
    'auth.register': 'Registrieren',
    'autotrader.button': 'KI Auto Geld',
    'advisors.elon.specialty': 'Visionäre Technologie & Marktdisruption',
    'advisors.warren.specialty': 'Wertanlage & Langfristiger Vermögensaufbau',
    'advisors.bill.specialty': 'Technologische Innovation & Philanthropische Investition',
    'advisors.vitalik.specialty': 'Blockchain & Dezentralisierung',
    'advisors.justin.specialty': 'TRON-Ökosystem & Marketing',
    'advisors.trump.specialty': 'Immobilien- & Markeninvestition'
  },
  
  it: {
    ...baseTranslations,
    'app.subtitle': 'Il Cervello Ultimo Rende Guadagnare Denaro Più Facile',
    'portfolio.total': 'Portafoglio Totale',
    'portfolio.change': 'Cambio 24h',
    'portfolio.trades': 'Trade Attivi',
    'market.overview': 'Panoramica del Mercato',
    'ai.communicate': 'Inizia Comunicazione',
    'status.live': 'Dati di Mercato in Tempo Reale',
    'advisor.confidence': 'Fiducia',
    'advisor.recommendation': 'Raccomandazione',
    'advisor.analysis': 'Analisi IA',
    'advisor.detailed': 'Ottieni Analisi Dettagliata',
    'advisor.featured': '⭐ In Evidenza',
    'wallet.connect': 'Connetti Portafoglio',
    'trading.strategy': 'Strategia di Trading',
    'button.refresh': 'Aggiorna Dati',
    'button.all_categories': 'Tutte le Categorie',
    'search.placeholder': 'Cerca criptovalute (es: Bitcoin, BTC)...',
    'language.switch': 'Cambio Lingua',
    'auth.login': 'Accedi',
    'auth.register': 'Registrati',
    'autotrader.button': 'IA Auto Denaro',
    'advisors.elon.specialty': 'Tecnologia Visionaria e Disruzione del Mercato',
    'advisors.warren.specialty': 'Investimento di Valore e Costruzione di Ricchezza a Lungo Termine',
    'advisors.bill.specialty': 'Innovazione Tecnologica e Investimento Filantropico',
    'advisors.vitalik.specialty': 'Blockchain e Decentralizzazione',
    'advisors.justin.specialty': 'Ecosistema TRON e Marketing',
    'advisors.trump.specialty': 'Investimento Immobiliare e di Brand'
  },
  
  pt: {
    ...baseTranslations,
    'app.subtitle': 'O Cérebro Definitivo Torna Ganhar Dinheiro Mais Fácil',
    'portfolio.total': 'Portfólio Total',
    'portfolio.change': 'Mudança 24h',
    'portfolio.trades': 'Negociações Ativas',
    'market.overview': 'Visão Geral do Mercado',
    'ai.communicate': 'Iniciar Comunicação',
    'status.live': 'Dados de Mercado em Tempo Real',
    'advisor.confidence': 'Confiança',
    'advisor.recommendation': 'Recomendação',
    'advisor.analysis': 'Análise IA',
    'advisor.detailed': 'Obter Análise Detalhada',
    'advisor.featured': '⭐ Destaque',
    'wallet.connect': 'Conectar Carteira',
    'trading.strategy': 'Estratégia de Trading',
    'button.refresh': 'Atualizar Dados',
    'button.all_categories': 'Todas as Categorias',
    'search.placeholder': 'Pesquisar criptomoedas (ex: Bitcoin, BTC)...',
    'language.switch': 'Mudança de Idioma',
    'auth.login': 'Entrar',
    'auth.register': 'Registrar',
    'autotrader.button': 'IA Auto Dinheiro',
    'advisors.elon.specialty': 'Tecnologia Visionária e Disrupção do Mercado',
    'advisors.warren.specialty': 'Investimento de Valor e Construção de Riqueza a Longo Prazo',
    'advisors.bill.specialty': 'Inovação Tecnológica e Investimento Filantrópico',
    'advisors.vitalik.specialty': 'Blockchain e Descentralização',
    'advisors.justin.specialty': 'Ecossistema TRON e Marketing',
    'advisors.trump.specialty': 'Investimento Imobiliário e de Marca'
  },
  
  ru: {
    ...baseTranslations,
    'app.subtitle': 'Идеальный Мозг Делает Заработок Денег Проще',
    'portfolio.total': 'Общий Портфель',
    'portfolio.change': 'Изменение 24ч',
    'portfolio.trades': 'Активные Сделки',
    'market.overview': 'Обзор Рынка',
    'ai.communicate': 'Начать Общение',
    'status.live': 'Данные Рынка в Реальном Времени',
    'advisor.confidence': 'Уверенность',
    'advisor.recommendation': 'Рекомендация',
    'advisor.analysis': 'ИИ Анализ',
    'advisor.detailed': 'Получить Детальный Анализ',
    'advisor.featured': '⭐ Рекомендуемый',
    'wallet.connect': 'Подключить Кошелек',
    'trading.strategy': 'Торговая Стратегия',
    'button.refresh': 'Обновить Данные',
    'button.all_categories': 'Все Категории',
    'search.placeholder': 'Искать криптовалюты (напр: Bitcoin, BTC)...',
    'language.switch': 'Смена Языка',
    'auth.login': 'Войти',
    'auth.register': 'Регистрация',
    'autotrader.button': 'ИИ Авто Деньги',
    'advisors.elon.specialty': 'Визионерские Технологии и Рыночная Дизрупция',
    'advisors.warren.specialty': 'Стоимостное Инвестирование и Долгосрочное Создание Богатства',
    'advisors.bill.specialty': 'Технологические Инновации и Филантропические Инвестиции',
    'advisors.vitalik.specialty': 'Блокчейн и Децентрализация',
    'advisors.justin.specialty': 'Экосистема TRON и Маркетинг',
    'advisors.trump.specialty': 'Недвижимость и Брендовые Инвестиции'
  },
  
  ar: {
    ...baseTranslations,
    'app.subtitle': 'العقل النهائي يجعل كسب المال أسهل',
    'portfolio.total': 'إجمالي المحفظة',
    'portfolio.change': 'التغيير خلال 24 ساعة',
    'portfolio.trades': 'الصفقات النشطة',
    'market.overview': 'نظرة عامة على السوق',
    'ai.communicate': 'بدء التواصل',
    'status.live': 'بيانات السوق في الوقت الفعلي',
    'advisor.confidence': 'الثقة',
    'advisor.recommendation': 'التوصية',
    'advisor.analysis': 'تحليل الذكاء الاصطناعي',
    'advisor.detailed': 'الحصول على تحليل مفصل',
    'advisor.featured': '⭐ مميز',
    'wallet.connect': 'ربط المحفظة',
    'trading.strategy': 'استراتيجية التداول',
    'button.refresh': 'تحديث البيانات',
    'button.all_categories': 'جميع الفئات',
    'search.placeholder': 'البحث عن العملات المشفرة (مثل: Bitcoin, BTC)...',
    'language.switch': 'تغيير اللغة',
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'التسجيل',
    'autotrader.button': 'المال التلقائي بالذكاء الاصطناعي',
    'advisors.elon.specialty': 'التكنولوجيا الرؤيوية وتعطيل السوق',
    'advisors.warren.specialty': 'الاستثمار القيمي وبناء الثروة طويلة المدى',
    'advisors.bill.specialty': 'الابتكار التكنولوجي والاستثمار الخيري',
    'advisors.vitalik.specialty': 'البلوك تشين واللامركزية',
    'advisors.justin.specialty': 'نظام TRON البيئي والتسويق',
    'advisors.trump.specialty': 'الاستثمار العقاري والعلامة التجارية'
  },
  
  hi: {
    ...baseTranslations,
    'app.subtitle': 'अल्टीमेट ब्रेन पैसा कमाना आसान बनाता है',
    'portfolio.total': 'कुल पोर्टफोलियो',
    'portfolio.change': '24 घंटे बदलाव',
    'portfolio.trades': 'सक्रिय ट्रेड्स',
    'market.overview': 'बाजार अवलोकन',
    'ai.communicate': 'संवाद शुरू करें',
    'status.live': 'रियल-टाइम बाजार डेटा',
    'advisor.confidence': 'विश्वास',
    'advisor.recommendation': 'सिफारिश',
    'advisor.analysis': 'AI विश्लेषण',
    'advisor.detailed': 'विस्तृत विश्लेषण प्राप्त करें',
    'advisor.featured': '⭐ फीचर्ड',
    'wallet.connect': 'वॉलेट कनेक्ट करें',
    'trading.strategy': 'ट्रेडिंग रणनीति',
    'button.refresh': 'डेटा रिफ्रेश करें',
    'button.all_categories': 'सभी श्रेणियां',
    'search.placeholder': 'क्रिप्टोकरेंसी खोजें (जैसे: Bitcoin, BTC)...',
    'language.switch': 'भाषा बदलाव',
    'auth.login': 'लॉगिन',
    'auth.register': 'रजिस्टर',
    'autotrader.button': 'AI ऑटो मनी',
    'advisors.elon.specialty': 'दूरदर्शी प्रौद्योगिकी और बाजार व्यवधान',
    'advisors.warren.specialty': 'मूल्य निवेश और दीर्घकालिक धन निर्माण',
    'advisors.bill.specialty': 'तकनीकी नवाचार और परोपकारी निवेश',
    'advisors.vitalik.specialty': 'ब्लॉकचेन और विकेंद्रीकरण',
    'advisors.justin.specialty': 'TRON इकोसिस्टम और मार्केटिंग',
    'advisors.trump.specialty': 'रियल एस्टेट और ब्रांड निवेश'
  },
  
  th: {
    ...baseTranslations,
    'app.subtitle': 'สมองขั้นสุดยอดทำให้การหาเงินง่ายขึ้น',
    'portfolio.total': 'พอร์ตโฟลิโอรวม',
    'portfolio.change': 'การเปลี่ยนแปลง 24 ชม.',
    'portfolio.trades': 'การซื้อขายที่กำลังดำเนินการ',
    'market.overview': 'ภาพรวมตลาด',
    'ai.communicate': 'เริ่มการสื่อสาร',
    'status.live': 'ข้อมูลตลาดแบบเรียลไทม์',
    'advisor.confidence': 'ความเชื่อมั่น',
    'advisor.recommendation': 'คำแนะนำ',
    'advisor.analysis': 'การวิเคราะห์ AI',
    'advisor.detailed': 'รับการวิเคราะห์โดยละเอียด',
    'advisor.featured': '⭐ แนะนำ',
    'wallet.connect': 'เชื่อมต่อกระเป๋าเงิน',
    'trading.strategy': 'กลยุทธ์การเทรด',
    'button.refresh': 'รีเฟรชข้อมูล',
    'button.all_categories': 'ทุกหมวดหมู่',
    'search.placeholder': 'ค้นหาสกุลเงินดิจิทัล (เช่น: Bitcoin, BTC)...',
    'language.switch': 'เปลี่ยนภาษา',
    'auth.login': 'เข้าสู่ระบบ',
    'auth.register': 'สมัครสมาชิก',
    'autotrader.button': 'AI Auto Money',
    'advisors.elon.specialty': 'เทคโนโลยีวิสัยทัศน์และการทำลายตลาด',
    'advisors.warren.specialty': 'การลงทุนแบบมูลค่าและการสร้างความมั่งคั่งระยะยาว',
    'advisors.bill.specialty': 'นวัตกรรมเทคโนโลยีและการลงทุนเพื่อการกุศล',
    'advisors.vitalik.specialty': 'บล็อกเชนและการกระจายอำนาจ',
    'advisors.justin.specialty': 'ระบบนิเวศ TRON และการตลาด',
    'advisors.trump.specialty': 'การลงทุนอสังหาริมทรัพย์และแบรนด์'
  },
  
  vi: {
    ...baseTranslations,
    'app.subtitle': 'Bộ Não Tối Thượng Làm Cho Kiếm Tiền Dễ Dàng Hơn',
    'portfolio.total': 'Tổng Danh Mục Đầu Tư',
    'portfolio.change': 'Thay Đổi 24h',
    'portfolio.trades': 'Giao Dịch Đang Hoạt Động',
    'market.overview': 'Tổng Quan Thị Trường',
    'ai.communicate': 'Bắt Đầu Giao Tiếp',
    'status.live': 'Dữ Liệu Thị Trường Thời Gian Thực',
    'advisor.confidence': 'Tin Cậy',
    'advisor.recommendation': 'Khuyến Nghị',
    'advisor.analysis': 'Phân Tích AI',
    'advisor.detailed': 'Nhận Phân Tích Chi Tiết',
    'advisor.featured': '⭐ Nổi Bật',
    'wallet.connect': 'Kết Nối Ví',
    'trading.strategy': 'Chiến Lược Giao Dịch',
    'button.refresh': 'Làm Mới Dữ Liệu',
    'button.all_categories': 'Tất Cả Danh Mục',
    'search.placeholder': 'Tìm kiếm tiền điện tử (ví dụ: Bitcoin, BTC)...',
    'language.switch': 'Chuyển Đổi Ngôn Ngữ',
    'auth.login': 'Đăng Nhập',
    'auth.register': 'Đăng Ký',
    'autotrader.button': 'AI Auto Money',
    'advisors.elon.specialty': 'Công Nghệ Tầm Nhìn và Gây Rối Loạn Thị Trường',
    'advisors.warren.specialty': 'Đầu Tư Giá Trị và Xây Dựng Tài Sản Dài Hạn',
    'advisors.bill.specialty': 'Đổi Mới Công Nghệ và Đầu Tư Từ Thiện',
    'advisors.vitalik.specialty': 'Blockchain và Phi Tập Trung',
    'advisors.justin.specialty': 'Hệ Sinh Thái TRON và Marketing',
    'advisors.trump.specialty': 'Đầu Tư Bất Động Sản và Thương Hiệu'
  },
  
  tr: {
    ...baseTranslations,
    'app.subtitle': 'Nihai Beyin Para Kazanmayı Daha Kolay Hale Getirir',
    'portfolio.total': 'Toplam Portföy',
    'portfolio.change': '24s Değişim',
    'portfolio.trades': 'Aktif İşlemler',
    'market.overview': 'Piyasa Genel Bakış',
    'ai.communicate': 'İletişimi Başlat',
    'status.live': 'Gerçek Zamanlı Piyasa Verileri',
    'advisor.confidence': 'Güven',
    'advisor.recommendation': 'Öneri',
    'advisor.analysis': 'AI Analizi',
    'advisor.detailed': 'Detaylı Analiz Al',
    'advisor.featured': '⭐ Öne Çıkan',
    'wallet.connect': 'Cüzdan Bağla',
    'trading.strategy': 'İşlem Stratejisi',
    'button.refresh': 'Verileri Yenile',
    'button.all_categories': 'Tüm Kategoriler',
    'search.placeholder': 'Kripto para arayın (örn: Bitcoin, BTC)...',
    'language.switch': 'Dil Değiştir',
    'auth.login': 'Giriş Yap',
    'auth.register': 'Kayıt Ol',
    'autotrader.button': 'AI Otomatik Para',
    'advisors.elon.specialty': 'Vizyoner Teknoloji ve Pazar Bozumu',
    'advisors.warren.specialty': 'Değer Yatırımı ve Uzun Vadeli Zenginlik Oluşturma',
    'advisors.bill.specialty': 'Teknoloji İnovasyonu ve Hayırsever Yatırım',
    'advisors.vitalik.specialty': 'Blockchain ve Merkeziyetsizlik',
    'advisors.justin.specialty': 'TRON Ekosistemi ve Pazarlama',
    'advisors.trump.specialty': 'Emlak ve Marka Yatırımı'
  },
  
  nl: {
    ...baseTranslations,
    'app.subtitle': 'Het Ultieme Brein Maakt Geld Verdienen Gemakkelijker',
    'portfolio.total': 'Totale Portfolio',
    'portfolio.change': '24u Verandering',
    'portfolio.trades': 'Actieve Trades',
    'market.overview': 'Marktoverzicht',
    'ai.communicate': 'Communicatie Starten',
    'status.live': 'Real-time Marktdata',
    'advisor.confidence': 'Vertrouwen',
    'advisor.recommendation': 'Aanbeveling',
    'advisor.analysis': 'AI Analyse',
    'advisor.detailed': 'Gedetailleerde Analyse Krijgen',
    'advisor.featured': '⭐ Uitgelicht',
    'wallet.connect': 'Wallet Verbinden',
    'trading.strategy': 'Trading Strategie',
    'button.refresh': 'Data Vernieuwen',
    'button.all_categories': 'Alle Categorieën',
    'search.placeholder': 'Zoek cryptocurrencies (bijv: Bitcoin, BTC)...',
    'language.switch': 'Taal Wisselen',
    'auth.login': 'Inloggen',
    'auth.register': 'Registreren',
    'autotrader.button': 'AI Auto Geld',
    'advisors.elon.specialty': 'Visionaire Technologie & Marktdisruptie',
    'advisors.warren.specialty': 'Waarde Investeren & Langetermijn Vermogensopbouw',
    'advisors.bill.specialty': 'Technologische Innovatie & Filantropische Investering',
    'advisors.vitalik.specialty': 'Blockchain & Decentralisatie',
    'advisors.justin.specialty': 'TRON Ecosysteem & Marketing',
    'advisors.trump.specialty': 'Vastgoed & Merk Investering'
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string, params?: Record<string, string>): string => {
    let translation = translations[language]?.[key] || translations['en'][key] || key;
    
    // Handle parameter substitution
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        translation = translation.replace(`{${param}}`, value);
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      currentLanguage: language,
      setLanguage, 
      t 
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
