import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh' | 'es' | 'ja' | 'ko' | 'fr' | 'de' | 'it' | 'pt' | 'ru' | 'ar' | 'hi' | 'th' | 'vi' | 'tr' | 'nl';

interface LanguageContextType {
  language: Language;
  currentLanguage: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-IN-1 Ultimate Brain Making Money Easier',
    'portfolio.total': 'Total Portfolio',
    'portfolio.change': '24h Change',
    'portfolio.trades': 'Active Trades',
    'market.overview': 'Market Overview',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Quick Actions',
    'actions.execute': 'Execute Trade',
    'actions.analysis': 'Portfolio Analysis',
    'actions.risk': 'Risk Assessment',
    'actions.alerts': 'Market Alerts',
    'status.live': 'Live Market Data',
    'advisor.confidence': 'Confident',
    'advisor.recommendation': 'Recommendation',
    'advisor.analysis': 'AI Analysis',
    'advisor.detailed': 'Get Detailed Analysis',
    'advisor.featured': '⭐ Featured',
    'ai.communicate': 'Start Communication',
    'wallet.connect': 'Connect Wallet', 
    'wallet.real': 'Real Wallet',
    'wallet.virtual': 'AI Virtual Portfolio',
    'trading.spot': 'Spot Trading',
    'trading.futures': 'Futures Trading',
    'trading.options': 'Options Trading',
    'ai.autotrader': 'AI Auto Trading',
    'button.refresh': 'Refresh Data',
    'button.show_top': 'Show Top 6',
    'button.all_categories': 'All Categories',
    'search.placeholder': 'Search cryptocurrencies (e.g.: Bitcoin, BTC)...',
    'search.clear': 'Clear Search',
    'search.showing': 'Showing',
    'search.of': '/',
    'search.currencies': 'cryptocurrencies',
    'search.filter': 'Search',
    'search.not_found': 'No cryptocurrencies found matching',
    'search.try_other': '',
    'search.suggestion': 'Please try searching with other keywords like Bitcoin, BTC',
    // Upcoming Advisors section
    'advisors.more_models': 'More Character Models',
    'advisors.not_alone': 'You Are Not Fighting Alone',
    'advisors.coming_soon': 'Coming Soon - Elite Warriors Assembling',
    'advisors.trump.name': 'Donald Trump',
    'advisors.trump.specialty': 'Business Empire Strategist',
    'advisors.trump.expertise': 'Business Empire',
    'advisors.trump.status': '🔧 In Development',
    'advisors.quantitative.name': 'Quantitative Trading Master',
    'advisors.quantitative.specialty': 'Algorithmic Trading Expert',
    'advisors.quantitative.expertise': 'Quantitative Strategy',
    'advisors.crypto.name': 'Crypto Currency King',
    'advisors.crypto.specialty': 'Web3 Investment Mentor',
    'advisors.crypto.expertise': 'Digital Assets',
    'advisors.macro.name': 'Macro Economic Master',
    'advisors.macro.specialty': 'Global Strategy Analyst',
    'advisors.macro.expertise': 'Macro Strategy',
    'advisors.coming_soon_status': '⏳ Coming Soon',
    // Wallet translations
    'wallet.connect_title': 'Connect Your Wallet',
    'wallet.select_description': 'Choose the most secure and reliable wallet to start trading and managing your portfolio',
    'wallet.connected': 'Connected',
    'wallet.address': 'Wallet Address:',
    'wallet.network': 'Network:',
    'wallet.view_explorer': 'View in Block Explorer',
    'wallet.disconnect': 'Disconnect',
    'wallet.connection_success': 'Wallet Connected Successfully',
    'wallet.connection_success_desc': 'Successfully connected to {wallet} - Now displaying real portfolio data',
    'wallet.connection_failed': 'Connection Failed',
    'wallet.connection_failed_desc': 'Wallet connection failed, please try again',
    'wallet.disconnected': 'Wallet Disconnected',
    'wallet.disconnected_desc': 'Successfully disconnected wallet - Switched back to AI virtual trading data',
    'wallet.address_copied': 'Address Copied',
    'wallet.address_copied_desc': 'Wallet address copied to clipboard',
    'wallet.category.all': 'All Wallets',
    'wallet.category.browser': 'Browser Extensions',
    'wallet.category.mobile': 'Mobile Apps',
    'wallet.category.hardware': 'Hardware Wallets',
    'wallet.category.institutional': 'Institutional',
    'wallet.security.extreme': 'Extreme Security',
    'wallet.security.very_high': 'Very High Security',
    'wallet.security.high': 'High Security',
    'wallet.market_share': 'Market Share',
    'wallet.supported_platforms': 'Supported Platforms:',
    'wallet.key_features': 'Key Features:',
    'wallet.more_platforms': '+{count} more',
    'wallet.more_features': '+{count} more',
    'wallet.recommended': 'Recommended',
    'wallet.installed': 'Installed',
    // Wallet descriptions
    'wallet.metamask.description': 'The world\'s most popular Ethereum wallet with extensive DApp support',
    'wallet.coinbase.description': 'Self-custody wallet by Coinbase with institutional-grade security',
    'wallet.walletconnect.description': 'Universal protocol connecting 300+ wallets to DApps',
    'wallet.trust.description': 'Multi-cryptocurrency wallet by Binance',
    'wallet.phantom.description': 'Leading Solana wallet with beautiful interface design',
    'wallet.tokenpocket.description': 'Asia\'s leading multi-chain wallet supporting 100+ blockchain ecosystems',
    'wallet.ledger.description': 'Industry-leading hardware wallet with bank-grade security protection',
    'wallet.trezor.description': 'Hardware wallet pioneer with open-source security solutions',
    'wallet.exodus.description': 'Beautiful multi-cryptocurrency wallet with built-in exchange',
    'wallet.atomic.description': 'Decentralized wallet supporting atomic swaps',
    'wallet.gnosis.description': 'Multi-signature wallet designed for institutions and teams',
    'wallet.argent.description': 'Smart contract wallet with social recovery support',
    'wallet.binance.description': 'Official Binance wallet with deep exchange integration',
    'wallet.okx.description': 'Web3 wallet by OKX exchange',
    'wallet.connect_button': 'Connect {wallet}'
  },
  zh: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3合1终极大脑让赚钱更简单',
    'portfolio.total': '总投资组合',
    'portfolio.change': '24小时变化',
    'portfolio.trades': '活跃交易',
    'market.overview': '市场概览',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': '快速操作',
    'actions.execute': '执行交易',
    'actions.analysis': '投资组合分析',
    'actions.risk': '风险评估',
    'actions.alerts': '市场提醒',
    'status.live': '实时市场数据',
    'advisor.confidence': '置信度',
    'advisor.recommendation': '推荐',
    'advisor.analysis': 'AI分析',
    'advisor.detailed': '获取详细分析',
    'advisor.featured': '⭐ 精选',
    'ai.communicate': '开始沟通',
    'wallet.connect': '连接钱包',
    'wallet.real': '真实钱包',
    'wallet.virtual': 'AI虚拟投资组合',
    'trading.spot': '现货交易',
    'trading.futures': '合约交易',
    'trading.options': '期权交易',
    'ai.autotrader': 'AI自动交易',
    'button.refresh': '刷新数据',
    'button.show_top': '显示前6个',
    'button.all_categories': '全部分类',
    'search.placeholder': '搜索加密货币 (例如: Bitcoin, BTC, 比特币)...',
    'search.clear': '清除搜索',
    'search.showing': '显示',
    'search.of': '/',
    'search.currencies': '种货币',
    'search.filter': '搜索',
    'search.not_found': '未找到匹配',
    'search.try_other': '的加密货币',
    'search.suggestion': '请尝试搜索其他关键词，如 Bitcoin、BTC 或比特币',
    // Upcoming Advisors section
    'advisors.more_models': '更多人物模型',
    'advisors.not_alone': '你不再是一个人战斗',
    'advisors.coming_soon': '敬请期待 - 顶级战友集结中',
    'advisors.trump.name': 'Donald Trump',
    'advisors.trump.specialty': '商业帝国战略大师',
    'advisors.trump.expertise': '商业帝国',
    'advisors.trump.status': '🔧 正在开发中',
    'advisors.quantitative.name': '量化交易大师',
    'advisors.quantitative.specialty': '算法交易专家',
    'advisors.quantitative.expertise': '量化策略',
    'advisors.crypto.name': '加密货币之王',
    'advisors.crypto.specialty': 'Web3投资导师',
    'advisors.crypto.expertise': '数字资产',
    'advisors.macro.name': '宏观经济大师',
    'advisors.macro.specialty': '全球策略分析师',
    'advisors.macro.expertise': '宏观策略',
    'advisors.coming_soon_status': '⏳ 即将到来',
    // Wallet translations
    'wallet.connect_title': '连接您的钱包',
    'wallet.select_description': '选择市场上最安全可靠的钱包开始交易和管理您的投资组合',
    'wallet.connected': '已连接',
    'wallet.address': '钱包地址:',
    'wallet.network': '网络:',
    'wallet.view_explorer': '在区块浏览器查看',
    'wallet.disconnect': '断开连接',
    'wallet.connection_success': '钱包连接成功',
    'wallet.connection_success_desc': '已成功连接到 {wallet} - 开始显示真实投资组合数据',
    'wallet.connection_failed': '连接失败',
    'wallet.connection_failed_desc': '钱包连接失败，请重试',
    'wallet.disconnected': '钱包已断开',
    'wallet.disconnected_desc': '已成功断开钱包连接 - 切换回AI虚拟交易数据',
    'wallet.address_copied': '地址已复制',
    'wallet.address_copied_desc': '钱包地址已复制到剪贴板',
    'wallet.category.all': '全部钱包',
    'wallet.category.browser': '浏览器扩展',
    'wallet.category.mobile': '移动应用',
    'wallet.category.hardware': '硬件钱包',
    'wallet.category.institutional': '机构级',
    'wallet.security.extreme': '极高安全',
    'wallet.security.very_high': '很高安全',
    'wallet.security.high': '高安全',
    'wallet.market_share': '市场份额',
    'wallet.supported_platforms': '支持平台:',
    'wallet.key_features': '主要功能:',
    'wallet.more_platforms': '+{count}更多',
    'wallet.more_features': '+{count}更多',
    'wallet.recommended': '推荐',
    'wallet.installed': '已安装',
    // Wallet descriptions
    'wallet.metamask.description': '全球最受欢迎的以太坊钱包，拥有广泛的DApp支持',
    'wallet.coinbase.description': 'Coinbase出品的自托管钱包，具有机构级安全性',
    'wallet.walletconnect.description': '连接300+钱包到DApps的通用协议',
    'wallet.trust.description': '币安旗下的多加密货币钱包',
    'wallet.phantom.description': '领先的Solana钱包，拥有精美的界面设计',
    'wallet.tokenpocket.description': '亚洲领先的多链钱包，支持100+公链生态',
    'wallet.ledger.description': '行业领先的硬件钱包，银行级安全保护',
    'wallet.trezor.description': '硬件钱包先驱，开源安全解决方案',
    'wallet.exodus.description': '精美的多加密货币钱包，内置交易功能',
    'wallet.atomic.description': '去中心化钱包，支持原子交换',
    'wallet.gnosis.description': '为机构和团队设计的多签名钱包',
    'wallet.argent.description': '智能合约钱包，支持社交恢复',
    'wallet.binance.description': '币安官方钱包，深度集成交易所功能',
    'wallet.okx.description': 'OKX交易所出品的Web3钱包',
    'wallet.connect_button': '连接 {wallet}'
  },
  es: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3 EN 1 Cerebro Ultimate que Hace Ganar Dinero Más Fácil',
    'portfolio.total': 'Portafolio Total',
    'portfolio.change': 'Cambio 24h',
    'portfolio.trades': 'Operaciones Activas',
    'market.overview': 'Resumen del Mercado',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Acciones Rápidas',
    'actions.execute': 'Ejecutar Operación',
    'actions.analysis': 'Análisis de Portafolio',
    'actions.risk': 'Evaluación de Riesgo',
    'actions.alerts': 'Alertas de Mercado',
    'status.live': 'Datos de Mercado en Vivo',
    'advisor.confidence': 'Confianza',
    'advisor.recommendation': 'Recomendación',
    'advisor.analysis': 'Análisis AI',
    'advisor.detailed': 'Obtener Análisis Detallado',
    'advisor.featured': '⭐ Destacado',
    'ai.communicate': 'Iniciar Comunicación',
    'wallet.connect': 'Conectar Billetera',
    'wallet.real': 'Portafolio Real',
    'wallet.virtual': 'Portafolio de Trading Virtual',
    'trading.spot': 'Trading al Contado',
    'trading.futures': 'Trading de Futuros',
    'trading.options': 'Trading de Opciones',
    'ai.autotrader': 'Trading Automático AI',
    // Upcoming Advisors section
    'advisors.more_models': 'Más Modelos de Personajes',
    'advisors.not_alone': 'No Luchas Solo',
    'advisors.coming_soon': 'Próximamente - Guerreros Élite Reuniéndose',
    'advisors.trump.name': 'Donald Trump',
    'advisors.trump.specialty': 'Estratega de Imperio Empresarial',
    'advisors.trump.expertise': 'Imperio Empresarial',
    'advisors.trump.status': '🔧 En Desarrollo',
    'advisors.quantitative.name': 'Maestro de Trading Cuantitativo',
    'advisors.quantitative.specialty': 'Experto en Trading Algorítmico',
    'advisors.quantitative.expertise': 'Estrategia Cuantitativa',
    'advisors.crypto.name': 'Rey de Criptomonedas',
    'advisors.crypto.specialty': 'Mentor de Inversión Web3',
    'advisors.crypto.expertise': 'Activos Digitales',
    'advisors.macro.name': 'Maestro Macroeconómico',
    'advisors.macro.specialty': 'Analista de Estrategia Global',
    'advisors.macro.expertise': 'Estrategia Macro',
    'advisors.coming_soon_status': '⏳ Próximamente'
  },
  ja: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-IN-1アルティメット・ブレインでお金稼ぎがより簡単に',
    'portfolio.total': '総ポートフォリオ',
    'portfolio.change': '24時間変動',
    'portfolio.trades': 'アクティブトレード',
    'market.overview': 'マーケット概要',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'クイックアクション',
    'actions.execute': 'トレード実行',
    'actions.analysis': 'ポートフォリオ分析',
    'actions.risk': 'リスク評価',
    'actions.alerts': 'マーケットアラート',
    'status.live': 'ライブマーケットデータ',
    'advisor.confidence': '信頼度',
    'advisor.recommendation': '推奨',
    'advisor.analysis': 'AI分析',
    'advisor.detailed': '詳細分析を取得',
    'advisor.featured': '⭐ 注目',
    'ai.communicate': 'コミュニケーション開始',
    'wallet.connect': 'ウォレット接続',
    'wallet.real': '実際のポートフォリオ',
    'wallet.virtual': 'バーチャルトレーディングポートフォリオ',
    'trading.spot': 'スポット取引',
    'trading.futures': '先物取引',
    'trading.options': 'オプション取引',
    'ai.autotrader': 'AI自動取引',
    // Upcoming Advisors section
    'advisors.more_models': 'より多くのキャラクターモデル',
    'advisors.not_alone': 'あなたは一人で戦っているわけではありません',
    'advisors.coming_soon': '近日公開 - エリート戦士集結中',
    'advisors.trump.name': 'Donald Trump',
    'advisors.trump.specialty': 'ビジネス帝国戦略家',
    'advisors.trump.expertise': 'ビジネス帝国',
    'advisors.trump.status': '🔧 開発中',
    'advisors.quantitative.name': 'クオンツトレーディングマスター',
    'advisors.quantitative.specialty': 'アルゴリズムトレーディング専門家',
    'advisors.quantitative.expertise': 'クオンツ戦略',
    'advisors.crypto.name': '暗号通貨王',
    'advisors.crypto.specialty': 'Web3投資メンター',
    'advisors.crypto.expertise': 'デジタル資産',
    'advisors.macro.name': 'マクロ経済マスター',
    'advisors.macro.specialty': 'グローバル戦略アナリスト',
    'advisors.macro.expertise': 'マクロ戦略',
    'advisors.coming_soon_status': '⏳ 近日公開'
  },
  ko: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-IN-1 궁극의 두뇌로 돈 벌기가 더 쉬워집니다',
    'portfolio.total': '총 포트폴리오',
    'portfolio.change': '24시간 변동',
    'portfolio.trades': '활성 거래',
    'market.overview': '시장 개요',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': '빠른 액션',
    'actions.execute': '거래 실행',
    'actions.analysis': '포트폴리오 분석',
    'actions.risk': '위험 평가',
    'actions.alerts': '시장 알림',
    'status.live': '실시간 시장 데이터',
    'advisor.confidence': '신뢰도',
    'advisor.recommendation': '추천',
    'advisor.analysis': 'AI 분석',
    'advisor.detailed': '상세 분석 받기',
    'advisor.featured': '⭐ 특집',
    'ai.communicate': '소통 시작',
    'wallet.connect': '지갑 연결',
    'wallet.real': '실제 포트폴리오',
    'wallet.virtual': '가상 거래 포트폴리오',
    'trading.spot': '현물 거래',
    'trading.futures': '선물 거래',
    'trading.options': '옵션 거래',
    'ai.autotrader': 'AI 자동 거래',
    // Upcoming Advisors section
    'advisors.more_models': '더 많은 캐릭터 모델',
    'advisors.not_alone': '당신은 혼자 싸우는 것이 아닙니다',
    'advisors.coming_soon': '곧 출시 - 엘리트 전사들 집결 중',
    'advisors.trump.name': 'Donald Trump',
    'advisors.trump.specialty': '비즈니스 제국 전략가',
    'advisors.trump.expertise': '비즈니스 제국',
    'advisors.trump.status': '🔧 개발 중',
    'advisors.quantitative.name': '퀀트 트레이딩 마스터',
    'advisors.quantitative.specialty': '알고리즘 트레이딩 전문가',
    'advisors.quantitative.expertise': '퀀트 전략',
    'advisors.crypto.name': '암호화폐 킹',
    'advisors.crypto.specialty': 'Web3 투자 멘토',
    'advisors.crypto.expertise': '디지털 자산',
    'advisors.macro.name': '거시경제 마스터',
    'advisors.macro.specialty': '글로벌 전략 분석가',
    'advisors.macro.expertise': '거시 전략',
    'advisors.coming_soon_status': '⏳ 곧 출시'
  },
  fr: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-EN-1 Cerveau Ultime Rendant l\'Argent Plus Facile',
    'portfolio.total': 'Portefeuille Total',
    'portfolio.change': 'Changement 24h',
    'portfolio.trades': 'Trades Actifs',
    'market.overview': 'Aperçu du Marché',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Actions Rapides',
    'actions.execute': 'Exécuter le Trade',
    'actions.analysis': 'Analyse du Portefeuille',
    'actions.risk': 'Évaluation des Risques',
    'actions.alerts': 'Alertes du Marché',
    'status.live': 'Données de Marché en Direct',
    'advisor.confidence': 'Confiance',
    'advisor.recommendation': 'Recommandation',
    'advisor.analysis': 'Analyse IA',
    'advisor.detailed': 'Obtenir une Analyse Détaillée',
    'advisor.featured': '⭐ Vedette',
    'ai.communicate': 'Commencer la Communication',
    'wallet.connect': 'Connecter le Portefeuille',
    'wallet.real': 'Portefeuille Réel',
    'wallet.virtual': 'Portefeuille de Trading Virtuel',
    'trading.spot': 'Trading au Comptant',
    'trading.futures': 'Trading de Contrats à Terme',
    'trading.options': 'Trading d\'Options',
    'ai.autotrader': 'Trading Automatique IA',
    // Upcoming Advisors section
    'advisors.more_models': 'Plus de Modèles de Personnages',
    'advisors.not_alone': 'Vous Ne Combattez Pas Seul',
    'advisors.coming_soon': 'Bientôt Disponible - Guerriers d\'Élite en Rassemblement',
    'advisors.trump.name': 'Donald Trump',
    'advisors.trump.specialty': 'Stratège d\'Empire Commercial',
    'advisors.trump.expertise': 'Empire Commercial',
    'advisors.trump.status': '🔧 En Développement',
    'advisors.quantitative.name': 'Maître du Trading Quantitatif',
    'advisors.quantitative.specialty': 'Expert en Trading Algorithmique',
    'advisors.quantitative.expertise': 'Stratégie Quantitative',
    'advisors.crypto.name': 'Roi des Cryptomonnaies',
    'advisors.crypto.specialty': 'Mentor d\'Investissement Web3',
    'advisors.crypto.expertise': 'Actifs Numériques',
    'advisors.macro.name': 'Maître Macroéconomique',
    'advisors.macro.specialty': 'Analyste de Stratégie Mondiale',
    'advisors.macro.expertise': 'Stratégie Macro',
    'advisors.coming_soon_status': '⏳ Bientôt Disponible'
  },
  de: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-IN-1 Ultimatives Gehirn Macht Geld Verdienen Einfacher',
    'portfolio.total': 'Gesamtportfolio',
    'portfolio.change': '24h Änderung',
    'portfolio.trades': 'Aktive Trades',
    'market.overview': 'Marktübersicht',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Schnelle Aktionen',
    'actions.execute': 'Trade Ausführen',
    'actions.analysis': 'Portfolio-Analyse',
    'actions.risk': 'Risikobewertung',
    'actions.alerts': 'Markt-Benachrichtigungen',
    'status.live': 'Live-Marktdaten',
    'advisor.confidence': 'Vertrauen',
    'advisor.recommendation': 'Empfehlung',
    'advisor.analysis': 'KI-Analyse',
    'advisor.detailed': 'Detaillierte Analyse Erhalten',
    'advisor.featured': '⭐ Empfohlen',
    'ai.communicate': 'Kommunikation Starten',
    'wallet.connect': 'Wallet Verbinden',
    'wallet.real': 'Echtes Portfolio',
    'wallet.virtual': 'Virtuelles Trading-Portfolio',
    'trading.spot': 'Spot-Trading',
    'trading.futures': 'Futures-Trading',
    'trading.options': 'Options-Trading',
    'ai.autotrader': 'KI-Auto-Trading',
    // Upcoming Advisors section
    'advisors.more_models': 'Mehr Charakter-Modelle',
    'advisors.not_alone': 'Sie Kämpfen Nicht Allein',
    'advisors.coming_soon': 'Demnächst - Elite-Krieger Versammeln Sich',
    'advisors.trump.name': 'Donald Trump',
    'advisors.trump.specialty': 'Business-Imperium-Stratege',
    'advisors.trump.expertise': 'Business-Imperium',
    'advisors.trump.status': '🔧 In Entwicklung',
    'advisors.quantitative.name': 'Quantitativer Trading-Meister',
    'advisors.quantitative.specialty': 'Algorithmus-Trading-Experte',
    'advisors.quantitative.expertise': 'Quantitative Strategie',
    'advisors.crypto.name': 'Kryptowährungs-König',
    'advisors.crypto.specialty': 'Web3-Investment-Mentor',
    'advisors.crypto.expertise': 'Digitale Vermögenswerte',
    'advisors.macro.name': 'Makroökonomischer Meister',
    'advisors.macro.specialty': 'Globaler Strategie-Analyst',
    'advisors.macro.expertise': 'Makro-Strategie',
    'advisors.coming_soon_status': '⏳ Demnächst'
  },
  it: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-IN-1 Cervello Supremo Rende Fare Soldi Più Facile',
    'portfolio.total': 'Portfolio Totale',
    'portfolio.change': 'Cambio 24h',
    'portfolio.trades': 'Trade Attivi',
    'market.overview': 'Panoramica del Mercato',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Azioni Rapide',
    'actions.execute': 'Esegui Trade',
    'actions.analysis': 'Analisi del Portfolio',
    'actions.risk': 'Valutazione del Rischio',
    'actions.alerts': 'Avvisi di Mercato',
    'status.live': 'Dati di Mercato in Tempo Reale',
    'advisor.confidence': 'Fiducia',
    'advisor.recommendation': 'Raccomandazione',
    'advisor.analysis': 'Analisi IA',
    'advisor.detailed': 'Ottieni Analisi Dettagliata',
    'advisor.featured': '⭐ In Evidenza',
    'ai.communicate': 'Inizia Comunicazione',
    'wallet.connect': 'Connetti Wallet',
    'wallet.real': 'Portfolio Reale',
    'wallet.virtual': 'Portfolio di Trading Virtuale',
    'trading.spot': 'Trading Spot',
    'trading.futures': 'Trading Futures',
    'trading.options': 'Trading Opzioni',
    'ai.autotrader': 'Trading Automatico IA',
    // Upcoming Advisors section
    'advisors.more_models': 'Più Modelli di Personaggi',
    'advisors.not_alone': 'Non Stai Combattendo Da Solo',
    'advisors.coming_soon': 'Prossimamente - Guerrieri d\'Élite si Stanno Radunando',
    'advisors.trump.name': 'Donald Trump',
    'advisors.trump.specialty': 'Stratega dell\'Impero Aziendale',
    'advisors.trump.expertise': 'Impero Aziendale',
    'advisors.trump.status': '🔧 In Sviluppo',
    'advisors.quantitative.name': 'Maestro del Trading Quantitativo',
    'advisors.quantitative.specialty': 'Esperto di Trading Algoritmico',
    'advisors.quantitative.expertise': 'Strategia Quantitativa',
    'advisors.crypto.name': 'Re delle Criptovalute',
    'advisors.crypto.specialty': 'Mentore di Investimenti Web3',
    'advisors.crypto.expertise': 'Asset Digitali',
    'advisors.macro.name': 'Maestro Macroeconomico',
    'advisors.macro.specialty': 'Analista di Strategia Globale',
    'advisors.macro.expertise': 'Strategia Macro',
    'advisors.coming_soon_status': '⏳ Prossimamente'
  },
  pt: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-EM-1 Cérebro Supremo Torna Ganhar Dinheiro Mais Fácil',
    'portfolio.total': 'Portfolio Total',
    'portfolio.change': 'Mudança 24h',
    'portfolio.trades': 'Trades Ativos',
    'market.overview': 'Visão Geral do Mercado',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Ações Rápidas',
    'actions.execute': 'Executar Trade',
    'actions.analysis': 'Análise do Portfolio',
    'actions.risk': 'Avaliação de Risco',
    'actions.alerts': 'Alertas do Mercado',
    'status.live': 'Dados de Mercado ao Vivo',
    'advisor.confidence': 'Confiança',
    'advisor.recommendation': 'Recomendação',
    'advisor.analysis': 'Análise IA',
    'advisor.detailed': 'Obter Análise Detalhada',
    'advisor.featured': '⭐ Destaque',
    'ai.communicate': 'Iniciar Comunicação',
    'wallet.connect': 'Conectar Carteira',
    'wallet.real': 'Portfolio Real',
    'wallet.virtual': 'Portfolio de Trading Virtual',
    'trading.spot': 'Trading à Vista',
    'trading.futures': 'Trading de Futuros',
    'trading.options': 'Trading de Opções',
    'ai.autotrader': 'Trading Automático IA',
    // Upcoming Advisors section
    'advisors.more_models': 'Mais Modelos de Personagens',
    'advisors.not_alone': 'Você Não Está Lutando Sozinho',
    'advisors.coming_soon': 'Em Breve - Guerreiros de Elite se Reunindo',
    'advisors.trump.name': 'Donald Trump',
    'advisors.trump.specialty': 'Estrategista do Império de Negócios',
    'advisors.trump.expertise': 'Império de Negócios',
    'advisors.trump.status': '🔧 Em Desenvolvimento',
    'advisors.quantitative.name': 'Mestre do Trading Quantitativo',
    'advisors.quantitative.specialty': 'Especialista em Trading Algorítmico',
    'advisors.quantitative.expertise': 'Estratégia Quantitativa',
    'advisors.crypto.name': 'Rei das Criptomoedas',
    'advisors.crypto.specialty': 'Mentor de Investimento Web3',
    'advisors.crypto.expertise': 'Ativos Digitais',
    'advisors.macro.name': 'Mestre Macroeconômico',
    'advisors.macro.specialty': 'Analista de Estratégia Global',
    'advisors.macro.expertise': 'Estratégia Macro',
    'advisors.coming_soon_status': '⏳ Em Breve'
  },
  ru: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-В-1 Верховный Мозг Делает Зарабатывание Денег Проще',
    'portfolio.total': 'Общий Портфель',
    'portfolio.change': 'Изменение за 24ч',
    'portfolio.trades': 'Активные Сделки',
    'market.overview': 'Обзор Рынка',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Быстрые Действия',
    'actions.execute': 'Выполнить Сделку',
    'actions.analysis': 'Анализ Портфеля',
    'actions.risk': 'Оценка Рисков',
    'actions.alerts': 'Рыночные Оповещения',
    'status.live': 'Данные Рынка в Реальном Времени',
    'advisor.confidence': 'Уверенность',
    'advisor.recommendation': 'Рекомендация',
    'advisor.analysis': 'ИИ Анализ',
    'advisor.detailed': 'Получить Детальный Анализ',
    'advisor.featured': '⭐ Рекомендуемое',
    'ai.communicate': 'Начать Общение',
    'wallet.connect': 'Подключить Кошелек',
    'wallet.real': 'Реальный Портфель',
    'wallet.virtual': 'Виртуальный Торговый Портфель',
    'trading.spot': 'Спот Торговля',
    'trading.futures': 'Фьючерсная Торговля',
    'trading.options': 'Опционная Торговля',
    'ai.autotrader': 'Автоматическая Торговля ИИ',
    // Upcoming Advisors section
    'advisors.more_models': 'Больше Моделей Персонажей',
    'advisors.not_alone': 'Вы Не Сражаетесь В Одиночку',
    'advisors.coming_soon': 'Скоро - Собираются Элитные Воины',
    'advisors.trump.name': 'Дональд Трамп',
    'advisors.trump.specialty': 'Стратег Бизнес-Империи',
    'advisors.trump.expertise': 'Бизнес-Империя',
    'advisors.trump.status': '🔧 В Разработке',
    'advisors.quantitative.name': 'Мастер Количественной Торговли',
    'advisors.quantitative.specialty': 'Эксперт по Алгоритмической Торговле',
    'advisors.quantitative.expertise': 'Количественная Стратегия',
    'advisors.crypto.name': 'Король Криптовалют',
    'advisors.crypto.specialty': 'Ментор Web3 Инвестиций',
    'advisors.crypto.expertise': 'Цифровые Активы',
    'advisors.macro.name': 'Макроэкономический Мастер',
    'advisors.macro.specialty': 'Аналитик Глобальной Стратегии',
    'advisors.macro.expertise': 'Макро Стратегия',
    'advisors.coming_soon_status': '⏳ Скоро'
  },
  ar: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-في-1 العقل الأعلى يجعل كسب المال أسهل',
    'portfolio.total': 'إجمالي المحفظة',
    'portfolio.change': 'تغيير 24 ساعة',
    'portfolio.trades': 'الصفقات النشطة',
    'market.overview': 'نظرة عامة على السوق',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'إجراءات سريعة',
    'actions.execute': 'تنفيذ الصفقة',
    'actions.analysis': 'تحليل المحفظة',
    'actions.risk': 'تقييم المخاطر',
    'actions.alerts': 'تنبيهات السوق',
    'status.live': 'بيانات السوق المباشرة',
    'advisor.confidence': 'الثقة',
    'advisor.recommendation': 'التوصية',
    'advisor.analysis': 'تحليل الذكاء الاصطناعي',
    'advisor.detailed': 'احصل على تحليل مفصل',
    'advisor.featured': '⭐ مميز',
    'ai.communicate': 'بدء التواصل',
    'wallet.connect': 'ربط المحفظة',
    'wallet.real': 'المحفظة الحقيقية',
    'wallet.virtual': 'محفظة التداول الافتراضية',
    'trading.spot': 'التداول الفوري',
    'trading.futures': 'تداول العقود الآجلة',
    'trading.options': 'تداول الخيارات',
    'ai.autotrader': 'التداول التلقائي بالذكاء الاصطناعي',
    // Upcoming Advisors section
    'advisors.more_models': 'المزيد من نماذج الشخصيات',
    'advisors.not_alone': 'أنت لست تقاتل وحدك',
    'advisors.coming_soon': 'قريباً - محاربو النخبة يتجمعون',
    'advisors.trump.name': 'دونالد ترامب',
    'advisors.trump.specialty': 'استراتيجي إمبراطورية الأعمال',
    'advisors.trump.expertise': 'إمبراطورية الأعمال',
    'advisors.trump.status': '🔧 قيد التطوير',
    'advisors.quantitative.name': 'أستاذ التداول الكمي',
    'advisors.quantitative.specialty': 'خبير التداول الخوارزمي',
    'advisors.quantitative.expertise': 'الاستراتيجية الكمية',
    'advisors.crypto.name': 'ملك العملات المشفرة',
    'advisors.crypto.specialty': 'مرشد استثمار Web3',
    'advisors.crypto.expertise': 'الأصول الرقمية',
    'advisors.macro.name': 'أستاذ الاقتصاد الكلي',
    'advisors.macro.specialty': 'محلل الاستراتيجية العالمية',
    'advisors.macro.expertise': 'الاستراتيجية الكلية',
    'advisors.coming_soon_status': '⏳ قريباً'
  },
  hi: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-इन-1 सुप्रीम ब्रेन पैसा कमाना आसान बनाता है',
    'portfolio.total': 'कुल पोर्टफोलियो',
    'portfolio.change': '24 घंटे का बदलाव',
    'portfolio.trades': 'सक्रिय ट्रेड्स',
    'market.overview': 'बाजार अवलोकन',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'त्वरित कार्य',
    'actions.execute': 'ट्रेड निष्पादित करें',
    'actions.analysis': 'पोर्टफोलियो विश्लेषण',
    'actions.risk': 'जोखिम मूल्यांकन',
    'actions.alerts': 'बाजार अलर्ट',
    'status.live': 'लाइव बाजार डेटा',
    'advisor.confidence': 'विश्वास',
    'advisor.recommendation': 'सिफारिश',
    'advisor.analysis': 'AI विश्लेषण',
    'advisor.detailed': 'विस्तृत विश्लेषण प्राप्त करें',
    'advisor.featured': '⭐ फीचर्ड',
    'ai.communicate': 'संवाद शुरू करें',
    'wallet.connect': 'वॉलेट कनेक्ट करें',
    'wallet.real': 'वास्तविक पोर्टफोलियो',
    'wallet.virtual': 'वर्चुअल ट्रेडिंग पोर्टफोलियो',
    'trading.spot': 'स्पॉट ट्रेडिंग',
    'trading.futures': 'फ्यूचर्स ट्रेडिंग',
    'trading.options': 'ऑप्शन्स ट्रेडिंग',
    'ai.autotrader': 'AI ऑटो ट्रेडिंग',
    // Upcoming Advisors section
    'advisors.more_models': 'अधिक चरित्र मॉडल',
    'advisors.not_alone': 'आप अकेले नहीं लड़ रहे हैं',
    'advisors.coming_soon': 'जल्द आ रहा है - अभिजात योद्धा एकत्रित हो रहे हैं',
    'advisors.trump.name': 'डोनाल्ड ट्रम्प',
    'advisors.trump.specialty': 'व्यापारिक साम्राज्य रणनीतिकार',
    'advisors.trump.expertise': 'व्यापारिक साम्राज्य',
    'advisors.trump.status': '🔧 विकास में',
    'advisors.quantitative.name': 'मात्रात्मक ट्रेडिंग मास्टर',
    'advisors.quantitative.specialty': 'एल्गोरिदमिक ट्रेडिंग विशेषज्ञ',
    'advisors.quantitative.expertise': 'मात्रात्मक रणनीति',
    'advisors.crypto.name': 'क्रिप्टोकरेंसी राजा',
    'advisors.crypto.specialty': 'Web3 निवेश गुरु',
    'advisors.crypto.expertise': 'डिजिटल संपत्ति',
    'advisors.macro.name': 'मैक्रो आर्थिक मास्टर',
    'advisors.macro.specialty': 'वैश्विक रणनीति विश्लेषक',
    'advisors.macro.expertise': 'मैक्रो रणनीति',
    'advisors.coming_soon_status': '⏳ जल्द आ रहा है'
  },
  th: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-ใน-1 สมองสูงสุดทำให้การหาเงินง่ายขึ้น',
    'portfolio.total': 'พอร์ตโฟลิโอรวม',
    'portfolio.change': 'การเปลี่ยนแปลง 24 ชม.',
    'portfolio.trades': 'เทรดที่ใช้งานอยู่',
    'market.overview': 'ภาพรวมตลาด',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'การดำเนินการด่วน',
    'actions.execute': 'ดำเนินการเทรด',
    'actions.analysis': 'วิเคราะห์พอร์ตโฟลิโอ',
    'actions.risk': 'ประเมินความเสี่ยง',
    'actions.alerts': 'การแจ้งเตือนตลาด',
    'status.live': 'ข้อมูลตลาดสด',
    'advisor.confidence': 'ความมั่นใจ',
    'advisor.recommendation': 'คำแนะนำ',
    'advisor.analysis': 'การวิเคราะห์ AI',
    'advisor.detailed': 'รับการวิเคราะห์โดยละเอียด',
    'advisor.featured': '⭐ แนะนำ',
    'ai.communicate': 'เริ่มการสื่อสาร',
    'wallet.connect': 'เชื่อมต่อกระเป๋าเงิน',
    'wallet.real': 'พอร์ตโฟลิโอจริง',
    'wallet.virtual': 'พอร์ตโฟลิโอเทรดเสมือน',
    'trading.spot': 'เทรดสปอต',
    'trading.futures': 'เทรดฟิวเจอร์ส',
    'trading.options': 'เทรดออปชั่น',
    'ai.autotrader': 'เทรดอัตโนมัติ AI',
    // Upcoming Advisors section
    'advisors.more_models': 'โมเดลตัวละครเพิ่มเติม',
    'advisors.not_alone': 'คุณไม่ได้ต่อสู้คนเดียว',
    'advisors.coming_soon': 'เร็วๆ นี้ - นักรบชั้นยอดกำลังมาเยือน',
    'advisors.trump.name': 'โดนัลด์ ทรัมป์',
    'advisors.trump.specialty': 'นักยุทธศาสตร์อาณาจักรธุรกิจ',
    'advisors.trump.expertise': 'อาณาจักรธุรกิจ',
    'advisors.trump.status': '🔧 กำลังพัฒนา',
    'advisors.quantitative.name': 'มาสเตอร์การเทรดเชิงปริมาณ',
    'advisors.quantitative.specialty': 'ผู้เชี่ยวชาญการเทรดอัลกอริทึม',
    'advisors.quantitative.expertise': 'กลยุทธ์เชิงปริมาณ',
    'advisors.crypto.name': 'ราชาคริปโตเคอร์เรนซี',
    'advisors.crypto.specialty': 'พี่เลี้ยงการลงทุน Web3',
    'advisors.crypto.expertise': 'สินทรัพย์ดิจิทัล',
    'advisors.macro.name': 'มาสเตอร์เศรษฐศาสตร์มหภาค',
    'advisors.macro.specialty': 'นักวิเคราะห์กลยุทธ์โลก',
    'advisors.macro.expertise': 'กลยุทธ์มหภาค',
    'advisors.coming_soon_status': '⏳ เร็วๆ นี้'
  },
  vi: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-TRONG-1 Bộ Não Tối Thượng Làm Kiếm Tiền Dễ Dàng Hơn',
    'portfolio.total': 'Tổng Danh Mục Đầu Tư',
    'portfolio.change': 'Thay Đổi 24h',
    'portfolio.trades': 'Giao Dịch Đang Hoạt Động',
    'market.overview': 'Tổng Quan Thị Trường',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Hành Động Nhanh',
    'actions.execute': 'Thực Hiện Giao Dịch',
    'actions.analysis': 'Phân Tích Danh Mục',
    'actions.risk': 'Đánh Giá Rủi Ro',
    'actions.alerts': 'Cảnh Báo Thị Trường',
    'status.live': 'Dữ Liệu Thị Trường Trực Tiếp',
    'advisor.confidence': 'Tin Tưởng',
    'advisor.recommendation': 'Khuyến Nghị',
    'advisor.analysis': 'Phân Tích AI',
    'advisor.detailed': 'Nhận Phân Tích Chi Tiết',
    'advisor.featured': '⭐ Nổi Bật',
    'ai.communicate': 'Bắt Đầu Giao Tiếp',
    'wallet.connect': 'Kết Nối Ví',
    'wallet.real': 'Danh Mục Thực',
    'wallet.virtual': 'Danh Mục Giao Dịch Ảo',
    'trading.spot': 'Giao Dịch Spot',
    'trading.futures': 'Giao Dịch Futures',
    'trading.options': 'Giao Dịch Options',
    'ai.autotrader': 'Giao Dịch Tự Động AI',
    // Upcoming Advisors section
    'advisors.more_models': 'Thêm Mô Hình Nhân Vật',
    'advisors.not_alone': 'Bạn Không Chiến Đấu Một Mình',
    'advisors.coming_soon': 'Sắp Ra Mắt - Các Chiến Binh Tinh Anh Đang Tập Hợp',
    'advisors.trump.name': 'Donald Trump',
    'advisors.trump.specialty': 'Chiến Lược Gia Đế Chế Kinh Doanh',
    'advisors.trump.expertise': 'Đế Chế Kinh Doanh',
    'advisors.trump.status': '🔧 Đang Phát Triển',
    'advisors.quantitative.name': 'Bậc Thầy Giao Dịch Định Lượng',
    'advisors.quantitative.specialty': 'Chuyên Gia Giao Dịch Thuật Toán',
    'advisors.quantitative.expertise': 'Chiến Lược Định Lượng',
    'advisors.crypto.name': 'Vua Tiền Điện Tử',
    'advisors.crypto.specialty': 'Cố Vấn Đầu Tư Web3',
    'advisors.crypto.expertise': 'Tài Sản Số',
    'advisors.macro.name': 'Bậc Thầy Kinh Tế Vĩ Mô',
    'advisors.macro.specialty': 'Nhà Phân Tích Chiến Lược Toàn Cầu',
    'advisors.macro.expertise': 'Chiến Lược Vĩ Mô',
    'advisors.coming_soon_status': '⏳ Sắp Ra Mắt'
  },
  tr: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-IN-1 Yüce Beyin Para Kazanmayı Daha Kolay Hale Getirir',
    'portfolio.total': 'Toplam Portföy',
    'portfolio.change': '24s Değişim',
    'portfolio.trades': 'Aktif İşlemler',
    'market.overview': 'Pazar Genel Bakış',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Hızlı Eylemler',
    'actions.execute': 'İşlem Gerçekleştir',
    'actions.analysis': 'Portföy Analizi',
    'actions.risk': 'Risk Değerlendirmesi',
    'actions.alerts': 'Pazar Uyarıları',
    'status.live': 'Canlı Pazar Verileri',
    'advisor.confidence': 'Güven',
    'advisor.recommendation': 'Öneri',
    'advisor.analysis': 'AI Analizi',
    'advisor.detailed': 'Detaylı Analiz Al',
    'advisor.featured': '⭐ Öne Çıkan',
    'ai.communicate': 'İletişim Başlat',
    'wallet.connect': 'Cüzdan Bağla',
    'wallet.real': 'Gerçek Portföy',
    'wallet.virtual': 'Sanal İşlem Portföyü',
    'trading.spot': 'Spot İşlem',
    'trading.futures': 'Vadeli İşlem',
    'trading.options': 'Opsiyon İşlemi',
    'ai.autotrader': 'AI Otomatik İşlem',
    // Upcoming Advisors section
    'advisors.more_models': 'Daha Fazla Karakter Modeli',
    'advisors.not_alone': 'Yalnız Savaşmıyorsunuz',
    'advisors.coming_soon': 'Yakında - Elit Savaşçılar Toplanıyor',
    'advisors.trump.name': 'Donald Trump',
    'advisors.trump.specialty': 'İş İmparatorluğu Stratejisti',
    'advisors.trump.expertise': 'İş İmparatorluğu',
    'advisors.trump.status': '🔧 Geliştiriliyor',
    'advisors.quantitative.name': 'Nicel Ticaret Ustası',
    'advisors.quantitative.specialty': 'Algoritmik Ticaret Uzmanı',
    'advisors.quantitative.expertise': 'Nicel Strateji',
    'advisors.crypto.name': 'Kripto Para Kralı',
    'advisors.crypto.specialty': 'Web3 Yatırım Mentoru',
    'advisors.crypto.expertise': 'Dijital Varlıklar',
    'advisors.macro.name': 'Makroekonomik Usta',
    'advisors.macro.specialty': 'Küresel Strateji Analisti',
    'advisors.macro.expertise': 'Makro Strateji',
    'advisors.coming_soon_status': '⏳ Yakında'
  },
  nl: {
    'app.title': 'Meta BrainX',
    'app.subtitle': '3-IN-1 Opperste Brein Maakt Geld Verdienen Makkelijker',
    'portfolio.total': 'Totale Portfolio',
    'portfolio.change': '24u Verandering',
    'portfolio.trades': 'Actieve Trades',
    'market.overview': 'Marktoverzicht',
    'ai.advisors': 'SUPREME BRAIN',
    'actions.title': 'Snelle Acties',
    'actions.execute': 'Trade Uitvoeren',
    'actions.analysis': 'Portfolio Analyse',
    'actions.risk': 'Risicobeoordeling',
    'actions.alerts': 'Marktwaarschuwingen',
    'status.live': 'Live Marktgegevens',
    'advisor.confidence': 'Vertrouwen',
    'advisor.recommendation': 'Aanbeveling',
    'advisor.analysis': 'AI Analyse',
    'advisor.detailed': 'Krijg Gedetailleerde Analyse',
    'advisor.featured': '⭐ Aanbevolen',
    'ai.communicate': 'Start Communicatie',
    'wallet.connect': 'Portemonnee Verbinden',
    'wallet.real': 'Echte Portfolio',
    'wallet.virtual': 'Virtuele Trading Portfolio',
    'trading.spot': 'Spot Trading',
    'trading.futures': 'Futures Trading',
    'trading.options': 'Opties Trading',
    'ai.autotrader': 'AI Auto Trading',
    // Upcoming Advisors section
    'advisors.more_models': 'Meer Karaktermodellen',
    'advisors.not_alone': 'Je Vecht Niet Alleen',
    'advisors.coming_soon': 'Binnenkort - Elite Krijgers Verzamelen',
    'advisors.trump.name': 'Donald Trump',
    'advisors.trump.specialty': 'Business Imperium Strateeg',
    'advisors.trump.expertise': 'Business Imperium',
    'advisors.trump.status': '🔧 In Ontwikkeling',
    'advisors.quantitative.name': 'Kwantitatieve Trading Meester',
    'advisors.quantitative.specialty': 'Algoritmische Trading Expert',
    'advisors.quantitative.expertise': 'Kwantitatieve Strategie',
    'advisors.crypto.name': 'Cryptocurrency Koning',
    'advisors.crypto.specialty': 'Web3 Investment Mentor',
    'advisors.crypto.expertise': 'Digitale Assets',
    'advisors.macro.name': 'Macro Economische Meester',
    'advisors.macro.specialty': 'Globale Strategie Analist',
    'advisors.macro.expertise': 'Macro Strategie',
    'advisors.coming_soon_status': '⏳ Binnenkort'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, currentLanguage: language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};