// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndacklcbzjfycwigdpfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kYWNrbGNiempmeWN3aWdkcGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTk2ODMsImV4cCI6MjA3MDczNTY4M30.RNp13cp1JWT0iDFyOtJCZfYQqHZkCuM1CBsXLuntK6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});